// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: user/user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PhotoFirebase } from "../general";
import { Timestamp } from "../google/protobuf/timestamp";
import {
  NotificationStatus,
  notificationStatusFromJSON,
  notificationStatusToJSON,
} from "../notifications/notification";

export const protobufPackage = "users";

export enum UserStatus {
  CREATED = 0,
  UNVERIFIED = 1,
  VERIFIED = 2,
  BLOCKED = 3,
  UNRECOGNIZED = -1,
}

export function userStatusFromJSON(object: any): UserStatus {
  switch (object) {
    case 0:
    case "CREATED":
      return UserStatus.CREATED;
    case 1:
    case "UNVERIFIED":
      return UserStatus.UNVERIFIED;
    case 2:
    case "VERIFIED":
      return UserStatus.VERIFIED;
    case 3:
    case "BLOCKED":
      return UserStatus.BLOCKED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserStatus.UNRECOGNIZED;
  }
}

export function userStatusToJSON(object: UserStatus): string {
  switch (object) {
    case UserStatus.CREATED:
      return "CREATED";
    case UserStatus.UNVERIFIED:
      return "UNVERIFIED";
    case UserStatus.VERIFIED:
      return "VERIFIED";
    case UserStatus.BLOCKED:
      return "BLOCKED";
    case UserStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SemurUser {
  id: string;
  email?: string | undefined;
  firstName: string;
  lastName: string;
  birthDate: Date | undefined;
  status: UserStatus;
  fcmAndroidTokens: string[];
  fcmIosTokens: string[];
  vapidWebTokens: string[];
  language?: string | undefined;
  organizationId?: string | undefined;
  photo: PhotoFirebase | undefined;
}

export interface UserNotification {
  id: string;
  userId: string;
  title: { [key: string]: string };
  description: { [key: string]: string };
  status: NotificationStatus;
  createdAt: Date | undefined;
  deathAt: Date | undefined;
}

export interface UserNotification_TitleEntry {
  key: string;
  value: string;
}

export interface UserNotification_DescriptionEntry {
  key: string;
  value: string;
}

function createBaseSemurUser(): SemurUser {
  return {
    id: "",
    email: undefined,
    firstName: "",
    lastName: "",
    birthDate: undefined,
    status: 0,
    fcmAndroidTokens: [],
    fcmIosTokens: [],
    vapidWebTokens: [],
    language: undefined,
    organizationId: undefined,
    photo: undefined,
  };
}

export const SemurUser: MessageFns<SemurUser> = {
  encode(message: SemurUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== undefined) {
      writer.uint32(18).string(message.email);
    }
    if (message.firstName !== "") {
      writer.uint32(26).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(34).string(message.lastName);
    }
    if (message.birthDate !== undefined) {
      Timestamp.encode(toTimestamp(message.birthDate), writer.uint32(42).fork()).join();
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    for (const v of message.fcmAndroidTokens) {
      writer.uint32(58).string(v!);
    }
    for (const v of message.fcmIosTokens) {
      writer.uint32(66).string(v!);
    }
    for (const v of message.vapidWebTokens) {
      writer.uint32(74).string(v!);
    }
    if (message.language !== undefined) {
      writer.uint32(82).string(message.language);
    }
    if (message.organizationId !== undefined) {
      writer.uint32(90).string(message.organizationId);
    }
    if (message.photo !== undefined) {
      PhotoFirebase.encode(message.photo, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SemurUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSemurUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.birthDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.fcmAndroidTokens.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.fcmIosTokens.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.vapidWebTokens.push(reader.string());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.organizationId = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.photo = PhotoFirebase.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SemurUser {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
      birthDate: isSet(object.birthDate) ? fromJsonTimestamp(object.birthDate) : undefined,
      status: isSet(object.status) ? userStatusFromJSON(object.status) : 0,
      fcmAndroidTokens: globalThis.Array.isArray(object?.fcmAndroidTokens)
        ? object.fcmAndroidTokens.map((e: any) => globalThis.String(e))
        : [],
      fcmIosTokens: globalThis.Array.isArray(object?.fcmIosTokens)
        ? object.fcmIosTokens.map((e: any) => globalThis.String(e))
        : [],
      vapidWebTokens: globalThis.Array.isArray(object?.vapidWebTokens)
        ? object.vapidWebTokens.map((e: any) => globalThis.String(e))
        : [],
      language: isSet(object.language) ? globalThis.String(object.language) : undefined,
      organizationId: isSet(object.organizationId) ? globalThis.String(object.organizationId) : undefined,
      photo: isSet(object.photo) ? PhotoFirebase.fromJSON(object.photo) : undefined,
    };
  },

  toJSON(message: SemurUser): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.birthDate !== undefined) {
      obj.birthDate = message.birthDate.toISOString();
    }
    if (message.status !== 0) {
      obj.status = userStatusToJSON(message.status);
    }
    if (message.fcmAndroidTokens?.length) {
      obj.fcmAndroidTokens = message.fcmAndroidTokens;
    }
    if (message.fcmIosTokens?.length) {
      obj.fcmIosTokens = message.fcmIosTokens;
    }
    if (message.vapidWebTokens?.length) {
      obj.vapidWebTokens = message.vapidWebTokens;
    }
    if (message.language !== undefined) {
      obj.language = message.language;
    }
    if (message.organizationId !== undefined) {
      obj.organizationId = message.organizationId;
    }
    if (message.photo !== undefined) {
      obj.photo = PhotoFirebase.toJSON(message.photo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SemurUser>, I>>(base?: I): SemurUser {
    return SemurUser.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SemurUser>, I>>(object: I): SemurUser {
    const message = createBaseSemurUser();
    message.id = object.id ?? "";
    message.email = object.email ?? undefined;
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.birthDate = object.birthDate ?? undefined;
    message.status = object.status ?? 0;
    message.fcmAndroidTokens = object.fcmAndroidTokens?.map((e) => e) || [];
    message.fcmIosTokens = object.fcmIosTokens?.map((e) => e) || [];
    message.vapidWebTokens = object.vapidWebTokens?.map((e) => e) || [];
    message.language = object.language ?? undefined;
    message.organizationId = object.organizationId ?? undefined;
    message.photo = (object.photo !== undefined && object.photo !== null)
      ? PhotoFirebase.fromPartial(object.photo)
      : undefined;
    return message;
  },
};

function createBaseUserNotification(): UserNotification {
  return { id: "", userId: "", title: {}, description: {}, status: 0, createdAt: undefined, deathAt: undefined };
}

export const UserNotification: MessageFns<UserNotification> = {
  encode(message: UserNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    Object.entries(message.title).forEach(([key, value]) => {
      UserNotification_TitleEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    Object.entries(message.description).forEach(([key, value]) => {
      UserNotification_DescriptionEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(50).fork()).join();
    }
    if (message.deathAt !== undefined) {
      Timestamp.encode(toTimestamp(message.deathAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = UserNotification_TitleEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.title[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = UserNotification_DescriptionEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.description[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.deathAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserNotification {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      title: isObject(object.title)
        ? Object.entries(object.title).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      description: isObject(object.description)
        ? Object.entries(object.description).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      status: isSet(object.status) ? notificationStatusFromJSON(object.status) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      deathAt: isSet(object.deathAt) ? fromJsonTimestamp(object.deathAt) : undefined,
    };
  },

  toJSON(message: UserNotification): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.title) {
      const entries = Object.entries(message.title);
      if (entries.length > 0) {
        obj.title = {};
        entries.forEach(([k, v]) => {
          obj.title[k] = v;
        });
      }
    }
    if (message.description) {
      const entries = Object.entries(message.description);
      if (entries.length > 0) {
        obj.description = {};
        entries.forEach(([k, v]) => {
          obj.description[k] = v;
        });
      }
    }
    if (message.status !== 0) {
      obj.status = notificationStatusToJSON(message.status);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.deathAt !== undefined) {
      obj.deathAt = message.deathAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserNotification>, I>>(base?: I): UserNotification {
    return UserNotification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserNotification>, I>>(object: I): UserNotification {
    const message = createBaseUserNotification();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.title = Object.entries(object.title ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.description = Object.entries(object.description ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.status = object.status ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.deathAt = object.deathAt ?? undefined;
    return message;
  },
};

function createBaseUserNotification_TitleEntry(): UserNotification_TitleEntry {
  return { key: "", value: "" };
}

export const UserNotification_TitleEntry: MessageFns<UserNotification_TitleEntry> = {
  encode(message: UserNotification_TitleEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserNotification_TitleEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserNotification_TitleEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserNotification_TitleEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: UserNotification_TitleEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserNotification_TitleEntry>, I>>(base?: I): UserNotification_TitleEntry {
    return UserNotification_TitleEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserNotification_TitleEntry>, I>>(object: I): UserNotification_TitleEntry {
    const message = createBaseUserNotification_TitleEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseUserNotification_DescriptionEntry(): UserNotification_DescriptionEntry {
  return { key: "", value: "" };
}

export const UserNotification_DescriptionEntry: MessageFns<UserNotification_DescriptionEntry> = {
  encode(message: UserNotification_DescriptionEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserNotification_DescriptionEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserNotification_DescriptionEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserNotification_DescriptionEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: UserNotification_DescriptionEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserNotification_DescriptionEntry>, I>>(
    base?: I,
  ): UserNotification_DescriptionEntry {
    return UserNotification_DescriptionEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserNotification_DescriptionEntry>, I>>(
    object: I,
  ): UserNotification_DescriptionEntry {
    const message = createBaseUserNotification_DescriptionEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
