// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: chats/chat.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AgentCategory, agentCategoryFromJSON, agentCategoryToJSON } from "../agents/agent";
import { EmailAssistantChatArtifacts, EmailAssistantChatMetadata } from "../agents/email_assistant";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "chats";

export enum ChatRole {
  USER = 0,
  MODEL = 1,
  SYSTEM = 2,
  TOOL = 3,
  UNRECOGNIZED = -1,
}

export function chatRoleFromJSON(object: any): ChatRole {
  switch (object) {
    case 0:
    case "USER":
      return ChatRole.USER;
    case 1:
    case "MODEL":
      return ChatRole.MODEL;
    case 2:
    case "SYSTEM":
      return ChatRole.SYSTEM;
    case 3:
    case "TOOL":
      return ChatRole.TOOL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ChatRole.UNRECOGNIZED;
  }
}

export function chatRoleToJSON(object: ChatRole): string {
  switch (object) {
    case ChatRole.USER:
      return "USER";
    case ChatRole.MODEL:
      return "MODEL";
    case ChatRole.SYSTEM:
      return "SYSTEM";
    case ChatRole.TOOL:
      return "TOOL";
    case ChatRole.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ChatMessage {
  id: number;
  role: ChatRole;
  author: string;
  content: string;
  followUpQuestions: string[];
  /** Metadata about the message */
  metadata?: ChatMetadata | undefined;
  artifacts?: ChatArtifacts | undefined;
  output?:
    | string
    | undefined;
  /** Tool-specific metadata */
  toolName?: string | undefined;
  toolRequestJson?: string | undefined;
  toolResponseJson?: string | undefined;
  createdAt: Date | undefined;
}

export interface ChatMetadata {
  emailAssistant: EmailAssistantChatMetadata | undefined;
}

export interface ChatArtifacts {
  emailAssistant: EmailAssistantChatArtifacts | undefined;
}

export interface ChatSession {
  id: string;
  userId: string;
  agentCategory: AgentCategory;
  currentMessageIndex: number;
  createdAt: Date | undefined;
  title: string;
}

function createBaseChatMessage(): ChatMessage {
  return {
    id: 0,
    role: 0,
    author: "",
    content: "",
    followUpQuestions: [],
    metadata: undefined,
    artifacts: undefined,
    output: undefined,
    toolName: undefined,
    toolRequestJson: undefined,
    toolResponseJson: undefined,
    createdAt: undefined,
  };
}

export const ChatMessage: MessageFns<ChatMessage> = {
  encode(message: ChatMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.role !== 0) {
      writer.uint32(16).int32(message.role);
    }
    if (message.author !== "") {
      writer.uint32(26).string(message.author);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    for (const v of message.followUpQuestions) {
      writer.uint32(42).string(v!);
    }
    if (message.metadata !== undefined) {
      ChatMetadata.encode(message.metadata, writer.uint32(50).fork()).join();
    }
    if (message.artifacts !== undefined) {
      ChatArtifacts.encode(message.artifacts, writer.uint32(58).fork()).join();
    }
    if (message.output !== undefined) {
      writer.uint32(66).string(message.output);
    }
    if (message.toolName !== undefined) {
      writer.uint32(74).string(message.toolName);
    }
    if (message.toolRequestJson !== undefined) {
      writer.uint32(82).string(message.toolRequestJson);
    }
    if (message.toolResponseJson !== undefined) {
      writer.uint32(90).string(message.toolResponseJson);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.followUpQuestions.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.metadata = ChatMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.artifacts = ChatArtifacts.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.output = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.toolName = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.toolRequestJson = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.toolResponseJson = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatMessage {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      role: isSet(object.role) ? chatRoleFromJSON(object.role) : 0,
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      followUpQuestions: globalThis.Array.isArray(object?.followUpQuestions)
        ? object.followUpQuestions.map((e: any) => globalThis.String(e))
        : [],
      metadata: isSet(object.metadata) ? ChatMetadata.fromJSON(object.metadata) : undefined,
      artifacts: isSet(object.artifacts) ? ChatArtifacts.fromJSON(object.artifacts) : undefined,
      output: isSet(object.output) ? globalThis.String(object.output) : undefined,
      toolName: isSet(object.toolName) ? globalThis.String(object.toolName) : undefined,
      toolRequestJson: isSet(object.toolRequestJson) ? globalThis.String(object.toolRequestJson) : undefined,
      toolResponseJson: isSet(object.toolResponseJson) ? globalThis.String(object.toolResponseJson) : undefined,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
    };
  },

  toJSON(message: ChatMessage): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.role !== 0) {
      obj.role = chatRoleToJSON(message.role);
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.followUpQuestions?.length) {
      obj.followUpQuestions = message.followUpQuestions;
    }
    if (message.metadata !== undefined) {
      obj.metadata = ChatMetadata.toJSON(message.metadata);
    }
    if (message.artifacts !== undefined) {
      obj.artifacts = ChatArtifacts.toJSON(message.artifacts);
    }
    if (message.output !== undefined) {
      obj.output = message.output;
    }
    if (message.toolName !== undefined) {
      obj.toolName = message.toolName;
    }
    if (message.toolRequestJson !== undefined) {
      obj.toolRequestJson = message.toolRequestJson;
    }
    if (message.toolResponseJson !== undefined) {
      obj.toolResponseJson = message.toolResponseJson;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatMessage>, I>>(base?: I): ChatMessage {
    return ChatMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessage>, I>>(object: I): ChatMessage {
    const message = createBaseChatMessage();
    message.id = object.id ?? 0;
    message.role = object.role ?? 0;
    message.author = object.author ?? "";
    message.content = object.content ?? "";
    message.followUpQuestions = object.followUpQuestions?.map((e) => e) || [];
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? ChatMetadata.fromPartial(object.metadata)
      : undefined;
    message.artifacts = (object.artifacts !== undefined && object.artifacts !== null)
      ? ChatArtifacts.fromPartial(object.artifacts)
      : undefined;
    message.output = object.output ?? undefined;
    message.toolName = object.toolName ?? undefined;
    message.toolRequestJson = object.toolRequestJson ?? undefined;
    message.toolResponseJson = object.toolResponseJson ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

function createBaseChatMetadata(): ChatMetadata {
  return { emailAssistant: undefined };
}

export const ChatMetadata: MessageFns<ChatMetadata> = {
  encode(message: ChatMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.emailAssistant !== undefined) {
      EmailAssistantChatMetadata.encode(message.emailAssistant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.emailAssistant = EmailAssistantChatMetadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatMetadata {
    return {
      emailAssistant: isSet(object.emailAssistant)
        ? EmailAssistantChatMetadata.fromJSON(object.emailAssistant)
        : undefined,
    };
  },

  toJSON(message: ChatMetadata): unknown {
    const obj: any = {};
    if (message.emailAssistant !== undefined) {
      obj.emailAssistant = EmailAssistantChatMetadata.toJSON(message.emailAssistant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatMetadata>, I>>(base?: I): ChatMetadata {
    return ChatMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMetadata>, I>>(object: I): ChatMetadata {
    const message = createBaseChatMetadata();
    message.emailAssistant = (object.emailAssistant !== undefined && object.emailAssistant !== null)
      ? EmailAssistantChatMetadata.fromPartial(object.emailAssistant)
      : undefined;
    return message;
  },
};

function createBaseChatArtifacts(): ChatArtifacts {
  return { emailAssistant: undefined };
}

export const ChatArtifacts: MessageFns<ChatArtifacts> = {
  encode(message: ChatArtifacts, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.emailAssistant !== undefined) {
      EmailAssistantChatArtifacts.encode(message.emailAssistant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatArtifacts {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatArtifacts();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.emailAssistant = EmailAssistantChatArtifacts.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatArtifacts {
    return {
      emailAssistant: isSet(object.emailAssistant)
        ? EmailAssistantChatArtifacts.fromJSON(object.emailAssistant)
        : undefined,
    };
  },

  toJSON(message: ChatArtifacts): unknown {
    const obj: any = {};
    if (message.emailAssistant !== undefined) {
      obj.emailAssistant = EmailAssistantChatArtifacts.toJSON(message.emailAssistant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatArtifacts>, I>>(base?: I): ChatArtifacts {
    return ChatArtifacts.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatArtifacts>, I>>(object: I): ChatArtifacts {
    const message = createBaseChatArtifacts();
    message.emailAssistant = (object.emailAssistant !== undefined && object.emailAssistant !== null)
      ? EmailAssistantChatArtifacts.fromPartial(object.emailAssistant)
      : undefined;
    return message;
  },
};

function createBaseChatSession(): ChatSession {
  return { id: "", userId: "", agentCategory: 0, currentMessageIndex: 0, createdAt: undefined, title: "" };
}

export const ChatSession: MessageFns<ChatSession> = {
  encode(message: ChatSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.agentCategory !== 0) {
      writer.uint32(24).int32(message.agentCategory);
    }
    if (message.currentMessageIndex !== 0) {
      writer.uint32(32).int32(message.currentMessageIndex);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(42).fork()).join();
    }
    if (message.title !== "") {
      writer.uint32(50).string(message.title);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.agentCategory = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.currentMessageIndex = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.title = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatSession {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      agentCategory: isSet(object.agentCategory) ? agentCategoryFromJSON(object.agentCategory) : 0,
      currentMessageIndex: isSet(object.currentMessageIndex) ? globalThis.Number(object.currentMessageIndex) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
    };
  },

  toJSON(message: ChatSession): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.agentCategory !== 0) {
      obj.agentCategory = agentCategoryToJSON(message.agentCategory);
    }
    if (message.currentMessageIndex !== 0) {
      obj.currentMessageIndex = Math.round(message.currentMessageIndex);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatSession>, I>>(base?: I): ChatSession {
    return ChatSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatSession>, I>>(object: I): ChatSession {
    const message = createBaseChatSession();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.agentCategory = object.agentCategory ?? 0;
    message.currentMessageIndex = object.currentMessageIndex ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.title = object.title ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
