// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: notifications/notification.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "notifications";

export enum NotificationStatus {
  UNREAD = 0,
  READ = 1,
  UNRECOGNIZED = -1,
}

export function notificationStatusFromJSON(object: any): NotificationStatus {
  switch (object) {
    case 0:
    case "UNREAD":
      return NotificationStatus.UNREAD;
    case 1:
    case "READ":
      return NotificationStatus.READ;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NotificationStatus.UNRECOGNIZED;
  }
}

export function notificationStatusToJSON(object: NotificationStatus): string {
  switch (object) {
    case NotificationStatus.UNREAD:
      return "UNREAD";
    case NotificationStatus.READ:
      return "READ";
    case NotificationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface NotificationApp {
  id: string;
  userId: string;
  title: { [key: string]: string };
  description: { [key: string]: string };
  status: NotificationStatus;
  createdAt: Date | undefined;
  deathAt: Date | undefined;
}

export interface NotificationApp_TitleEntry {
  key: string;
  value: string;
}

export interface NotificationApp_DescriptionEntry {
  key: string;
  value: string;
}

function createBaseNotificationApp(): NotificationApp {
  return { id: "", userId: "", title: {}, description: {}, status: 0, createdAt: undefined, deathAt: undefined };
}

export const NotificationApp: MessageFns<NotificationApp> = {
  encode(message: NotificationApp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    Object.entries(message.title).forEach(([key, value]) => {
      NotificationApp_TitleEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    Object.entries(message.description).forEach(([key, value]) => {
      NotificationApp_DescriptionEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(50).fork()).join();
    }
    if (message.deathAt !== undefined) {
      Timestamp.encode(toTimestamp(message.deathAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotificationApp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotificationApp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = NotificationApp_TitleEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.title[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = NotificationApp_DescriptionEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.description[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.deathAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NotificationApp {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      title: isObject(object.title)
        ? Object.entries(object.title).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      description: isObject(object.description)
        ? Object.entries(object.description).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      status: isSet(object.status) ? notificationStatusFromJSON(object.status) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      deathAt: isSet(object.deathAt) ? fromJsonTimestamp(object.deathAt) : undefined,
    };
  },

  toJSON(message: NotificationApp): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.title) {
      const entries = Object.entries(message.title);
      if (entries.length > 0) {
        obj.title = {};
        entries.forEach(([k, v]) => {
          obj.title[k] = v;
        });
      }
    }
    if (message.description) {
      const entries = Object.entries(message.description);
      if (entries.length > 0) {
        obj.description = {};
        entries.forEach(([k, v]) => {
          obj.description[k] = v;
        });
      }
    }
    if (message.status !== 0) {
      obj.status = notificationStatusToJSON(message.status);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.deathAt !== undefined) {
      obj.deathAt = message.deathAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NotificationApp>, I>>(base?: I): NotificationApp {
    return NotificationApp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NotificationApp>, I>>(object: I): NotificationApp {
    const message = createBaseNotificationApp();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.title = Object.entries(object.title ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.description = Object.entries(object.description ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.status = object.status ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.deathAt = object.deathAt ?? undefined;
    return message;
  },
};

function createBaseNotificationApp_TitleEntry(): NotificationApp_TitleEntry {
  return { key: "", value: "" };
}

export const NotificationApp_TitleEntry: MessageFns<NotificationApp_TitleEntry> = {
  encode(message: NotificationApp_TitleEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotificationApp_TitleEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotificationApp_TitleEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NotificationApp_TitleEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: NotificationApp_TitleEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NotificationApp_TitleEntry>, I>>(base?: I): NotificationApp_TitleEntry {
    return NotificationApp_TitleEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NotificationApp_TitleEntry>, I>>(object: I): NotificationApp_TitleEntry {
    const message = createBaseNotificationApp_TitleEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseNotificationApp_DescriptionEntry(): NotificationApp_DescriptionEntry {
  return { key: "", value: "" };
}

export const NotificationApp_DescriptionEntry: MessageFns<NotificationApp_DescriptionEntry> = {
  encode(message: NotificationApp_DescriptionEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotificationApp_DescriptionEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotificationApp_DescriptionEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NotificationApp_DescriptionEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: NotificationApp_DescriptionEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NotificationApp_DescriptionEntry>, I>>(
    base?: I,
  ): NotificationApp_DescriptionEntry {
    return NotificationApp_DescriptionEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NotificationApp_DescriptionEntry>, I>>(
    object: I,
  ): NotificationApp_DescriptionEntry {
    const message = createBaseNotificationApp_DescriptionEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
