// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: semur-engine/nango-engine/google-mail_engine.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SemurEngineErrorCode, semurEngineErrorCodeFromJSON, semurEngineErrorCodeToJSON } from "../semur_engine";

export const protobufPackage = "semur_engine";

/** User Connections */
export interface NangoGoogleMailSendEmailRequest {
  userId: string;
  to: string;
  headers: { [key: string]: string };
  subject?: string | undefined;
  body: string;
}

export interface NangoGoogleMailSendEmailRequest_HeadersEntry {
  key: string;
  value: string;
}

export interface NangoGoogleMailSendEmailResponse {
  error: SemurEngineErrorCode;
  message: string;
}

function createBaseNangoGoogleMailSendEmailRequest(): NangoGoogleMailSendEmailRequest {
  return { userId: "", to: "", headers: {}, subject: undefined, body: "" };
}

export const NangoGoogleMailSendEmailRequest: MessageFns<NangoGoogleMailSendEmailRequest> = {
  encode(message: NangoGoogleMailSendEmailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.to !== "") {
      writer.uint32(18).string(message.to);
    }
    Object.entries(message.headers).forEach(([key, value]) => {
      NangoGoogleMailSendEmailRequest_HeadersEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.subject !== undefined) {
      writer.uint32(34).string(message.subject);
    }
    if (message.body !== "") {
      writer.uint32(42).string(message.body);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoGoogleMailSendEmailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoGoogleMailSendEmailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = NangoGoogleMailSendEmailRequest_HeadersEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.headers[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.body = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoGoogleMailSendEmailRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      headers: isObject(object.headers)
        ? Object.entries(object.headers).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      subject: isSet(object.subject) ? globalThis.String(object.subject) : undefined,
      body: isSet(object.body) ? globalThis.String(object.body) : "",
    };
  },

  toJSON(message: NangoGoogleMailSendEmailRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.headers) {
      const entries = Object.entries(message.headers);
      if (entries.length > 0) {
        obj.headers = {};
        entries.forEach(([k, v]) => {
          obj.headers[k] = v;
        });
      }
    }
    if (message.subject !== undefined) {
      obj.subject = message.subject;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoGoogleMailSendEmailRequest>, I>>(base?: I): NangoGoogleMailSendEmailRequest {
    return NangoGoogleMailSendEmailRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoGoogleMailSendEmailRequest>, I>>(
    object: I,
  ): NangoGoogleMailSendEmailRequest {
    const message = createBaseNangoGoogleMailSendEmailRequest();
    message.userId = object.userId ?? "";
    message.to = object.to ?? "";
    message.headers = Object.entries(object.headers ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.subject = object.subject ?? undefined;
    message.body = object.body ?? "";
    return message;
  },
};

function createBaseNangoGoogleMailSendEmailRequest_HeadersEntry(): NangoGoogleMailSendEmailRequest_HeadersEntry {
  return { key: "", value: "" };
}

export const NangoGoogleMailSendEmailRequest_HeadersEntry: MessageFns<NangoGoogleMailSendEmailRequest_HeadersEntry> = {
  encode(
    message: NangoGoogleMailSendEmailRequest_HeadersEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoGoogleMailSendEmailRequest_HeadersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoGoogleMailSendEmailRequest_HeadersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoGoogleMailSendEmailRequest_HeadersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: NangoGoogleMailSendEmailRequest_HeadersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoGoogleMailSendEmailRequest_HeadersEntry>, I>>(
    base?: I,
  ): NangoGoogleMailSendEmailRequest_HeadersEntry {
    return NangoGoogleMailSendEmailRequest_HeadersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoGoogleMailSendEmailRequest_HeadersEntry>, I>>(
    object: I,
  ): NangoGoogleMailSendEmailRequest_HeadersEntry {
    const message = createBaseNangoGoogleMailSendEmailRequest_HeadersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseNangoGoogleMailSendEmailResponse(): NangoGoogleMailSendEmailResponse {
  return { error: 0, message: "" };
}

export const NangoGoogleMailSendEmailResponse: MessageFns<NangoGoogleMailSendEmailResponse> = {
  encode(message: NangoGoogleMailSendEmailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== 0) {
      writer.uint32(8).int32(message.error);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoGoogleMailSendEmailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoGoogleMailSendEmailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.error = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoGoogleMailSendEmailResponse {
    return {
      error: isSet(object.error) ? semurEngineErrorCodeFromJSON(object.error) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: NangoGoogleMailSendEmailResponse): unknown {
    const obj: any = {};
    if (message.error !== 0) {
      obj.error = semurEngineErrorCodeToJSON(message.error);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoGoogleMailSendEmailResponse>, I>>(
    base?: I,
  ): NangoGoogleMailSendEmailResponse {
    return NangoGoogleMailSendEmailResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoGoogleMailSendEmailResponse>, I>>(
    object: I,
  ): NangoGoogleMailSendEmailResponse {
    const message = createBaseNangoGoogleMailSendEmailResponse();
    message.error = object.error ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
