// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: semur-engine/nango-engine/nango_engine.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../google/protobuf/timestamp";
import { NangoConnectionPublic } from "../../nango/nango";
import { SyncMode, syncModeFromJSON, syncModeToJSON } from "../../syncs/sync";
import { SemurEngineErrorCode, semurEngineErrorCodeFromJSON, semurEngineErrorCodeToJSON } from "../semur_engine";

export const protobufPackage = "semur_engine";

/** User Connections */
export interface NangoUserConnectionsRequest {
  userId: string;
  organizationId?: string | undefined;
}

export interface NangoUserConnectionsResponse {
  error: SemurEngineErrorCode;
  message: string;
  connections: NangoConnectionPublic[];
}

/** Session Token */
export interface NangoSessionTokenRequest {
  integrationId: string;
  userId: string;
  userEmail?: string | undefined;
  userName?: string | undefined;
}

export interface NangoSessionTokenResponse {
  error: SemurEngineErrorCode;
  message: string;
  token: string;
}

/** Webhook */
export interface NangoConnectionWebhookEndUser {
  endUserId: string;
  organizationId?: string | undefined;
}

export interface NangoConnectionWebhookError {
  type: string;
  message: string;
}

export interface NangoConnectionWebhookRequest {
  type: string;
  operation: string;
  connectionId: string;
  authMode: string;
  providerConfigKey: string;
  provider: string;
  environment: string;
  success: boolean;
  endUser?: NangoConnectionWebhookEndUser | undefined;
  error?: NangoConnectionWebhookError | undefined;
}

export interface NangoSyncWebhookRequest {
  type: string;
  connectionId: string;
  providerConfigKey: string;
  syncName: string;
  model: string;
  syncType: string;
  success: boolean;
  modifiedAfter: Date | undefined;
  responseResults: NangoSyncWebhookResponseResults | undefined;
}

export interface NangoSyncWebhookResponseResults {
  added: number;
  updated: number;
  deleted: number;
}

export interface NangoTriggerSyncRequest {
  providerConfigKey: string;
  syncs: string[];
  connectionId: string;
  syncMode: SyncMode;
  userId: string;
}

export interface NangoTriggerSyncResponse {
  error: SemurEngineErrorCode;
  message: string;
}

function createBaseNangoUserConnectionsRequest(): NangoUserConnectionsRequest {
  return { userId: "", organizationId: undefined };
}

export const NangoUserConnectionsRequest: MessageFns<NangoUserConnectionsRequest> = {
  encode(message: NangoUserConnectionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.organizationId !== undefined) {
      writer.uint32(18).string(message.organizationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoUserConnectionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoUserConnectionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.organizationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoUserConnectionsRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      organizationId: isSet(object.organizationId) ? globalThis.String(object.organizationId) : undefined,
    };
  },

  toJSON(message: NangoUserConnectionsRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.organizationId !== undefined) {
      obj.organizationId = message.organizationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoUserConnectionsRequest>, I>>(base?: I): NangoUserConnectionsRequest {
    return NangoUserConnectionsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoUserConnectionsRequest>, I>>(object: I): NangoUserConnectionsRequest {
    const message = createBaseNangoUserConnectionsRequest();
    message.userId = object.userId ?? "";
    message.organizationId = object.organizationId ?? undefined;
    return message;
  },
};

function createBaseNangoUserConnectionsResponse(): NangoUserConnectionsResponse {
  return { error: 0, message: "", connections: [] };
}

export const NangoUserConnectionsResponse: MessageFns<NangoUserConnectionsResponse> = {
  encode(message: NangoUserConnectionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== 0) {
      writer.uint32(8).int32(message.error);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    for (const v of message.connections) {
      NangoConnectionPublic.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoUserConnectionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoUserConnectionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.error = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.connections.push(NangoConnectionPublic.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoUserConnectionsResponse {
    return {
      error: isSet(object.error) ? semurEngineErrorCodeFromJSON(object.error) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      connections: globalThis.Array.isArray(object?.connections)
        ? object.connections.map((e: any) => NangoConnectionPublic.fromJSON(e))
        : [],
    };
  },

  toJSON(message: NangoUserConnectionsResponse): unknown {
    const obj: any = {};
    if (message.error !== 0) {
      obj.error = semurEngineErrorCodeToJSON(message.error);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.connections?.length) {
      obj.connections = message.connections.map((e) => NangoConnectionPublic.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoUserConnectionsResponse>, I>>(base?: I): NangoUserConnectionsResponse {
    return NangoUserConnectionsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoUserConnectionsResponse>, I>>(object: I): NangoUserConnectionsResponse {
    const message = createBaseNangoUserConnectionsResponse();
    message.error = object.error ?? 0;
    message.message = object.message ?? "";
    message.connections = object.connections?.map((e) => NangoConnectionPublic.fromPartial(e)) || [];
    return message;
  },
};

function createBaseNangoSessionTokenRequest(): NangoSessionTokenRequest {
  return { integrationId: "", userId: "", userEmail: undefined, userName: undefined };
}

export const NangoSessionTokenRequest: MessageFns<NangoSessionTokenRequest> = {
  encode(message: NangoSessionTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.integrationId !== "") {
      writer.uint32(10).string(message.integrationId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.userEmail !== undefined) {
      writer.uint32(26).string(message.userEmail);
    }
    if (message.userName !== undefined) {
      writer.uint32(34).string(message.userName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoSessionTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoSessionTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.integrationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userEmail = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoSessionTokenRequest {
    return {
      integrationId: isSet(object.integrationId) ? globalThis.String(object.integrationId) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      userEmail: isSet(object.userEmail) ? globalThis.String(object.userEmail) : undefined,
      userName: isSet(object.userName) ? globalThis.String(object.userName) : undefined,
    };
  },

  toJSON(message: NangoSessionTokenRequest): unknown {
    const obj: any = {};
    if (message.integrationId !== "") {
      obj.integrationId = message.integrationId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.userEmail !== undefined) {
      obj.userEmail = message.userEmail;
    }
    if (message.userName !== undefined) {
      obj.userName = message.userName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoSessionTokenRequest>, I>>(base?: I): NangoSessionTokenRequest {
    return NangoSessionTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoSessionTokenRequest>, I>>(object: I): NangoSessionTokenRequest {
    const message = createBaseNangoSessionTokenRequest();
    message.integrationId = object.integrationId ?? "";
    message.userId = object.userId ?? "";
    message.userEmail = object.userEmail ?? undefined;
    message.userName = object.userName ?? undefined;
    return message;
  },
};

function createBaseNangoSessionTokenResponse(): NangoSessionTokenResponse {
  return { error: 0, message: "", token: "" };
}

export const NangoSessionTokenResponse: MessageFns<NangoSessionTokenResponse> = {
  encode(message: NangoSessionTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== 0) {
      writer.uint32(8).int32(message.error);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.token !== "") {
      writer.uint32(26).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoSessionTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoSessionTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.error = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoSessionTokenResponse {
    return {
      error: isSet(object.error) ? semurEngineErrorCodeFromJSON(object.error) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: NangoSessionTokenResponse): unknown {
    const obj: any = {};
    if (message.error !== 0) {
      obj.error = semurEngineErrorCodeToJSON(message.error);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoSessionTokenResponse>, I>>(base?: I): NangoSessionTokenResponse {
    return NangoSessionTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoSessionTokenResponse>, I>>(object: I): NangoSessionTokenResponse {
    const message = createBaseNangoSessionTokenResponse();
    message.error = object.error ?? 0;
    message.message = object.message ?? "";
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseNangoConnectionWebhookEndUser(): NangoConnectionWebhookEndUser {
  return { endUserId: "", organizationId: undefined };
}

export const NangoConnectionWebhookEndUser: MessageFns<NangoConnectionWebhookEndUser> = {
  encode(message: NangoConnectionWebhookEndUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.endUserId !== "") {
      writer.uint32(10).string(message.endUserId);
    }
    if (message.organizationId !== undefined) {
      writer.uint32(18).string(message.organizationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoConnectionWebhookEndUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoConnectionWebhookEndUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.endUserId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.organizationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoConnectionWebhookEndUser {
    return {
      endUserId: isSet(object.endUserId) ? globalThis.String(object.endUserId) : "",
      organizationId: isSet(object.organizationId) ? globalThis.String(object.organizationId) : undefined,
    };
  },

  toJSON(message: NangoConnectionWebhookEndUser): unknown {
    const obj: any = {};
    if (message.endUserId !== "") {
      obj.endUserId = message.endUserId;
    }
    if (message.organizationId !== undefined) {
      obj.organizationId = message.organizationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoConnectionWebhookEndUser>, I>>(base?: I): NangoConnectionWebhookEndUser {
    return NangoConnectionWebhookEndUser.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoConnectionWebhookEndUser>, I>>(
    object: I,
  ): NangoConnectionWebhookEndUser {
    const message = createBaseNangoConnectionWebhookEndUser();
    message.endUserId = object.endUserId ?? "";
    message.organizationId = object.organizationId ?? undefined;
    return message;
  },
};

function createBaseNangoConnectionWebhookError(): NangoConnectionWebhookError {
  return { type: "", message: "" };
}

export const NangoConnectionWebhookError: MessageFns<NangoConnectionWebhookError> = {
  encode(message: NangoConnectionWebhookError, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoConnectionWebhookError {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoConnectionWebhookError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoConnectionWebhookError {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: NangoConnectionWebhookError): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoConnectionWebhookError>, I>>(base?: I): NangoConnectionWebhookError {
    return NangoConnectionWebhookError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoConnectionWebhookError>, I>>(object: I): NangoConnectionWebhookError {
    const message = createBaseNangoConnectionWebhookError();
    message.type = object.type ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseNangoConnectionWebhookRequest(): NangoConnectionWebhookRequest {
  return {
    type: "",
    operation: "",
    connectionId: "",
    authMode: "",
    providerConfigKey: "",
    provider: "",
    environment: "",
    success: false,
    endUser: undefined,
    error: undefined,
  };
}

export const NangoConnectionWebhookRequest: MessageFns<NangoConnectionWebhookRequest> = {
  encode(message: NangoConnectionWebhookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.operation !== "") {
      writer.uint32(18).string(message.operation);
    }
    if (message.connectionId !== "") {
      writer.uint32(26).string(message.connectionId);
    }
    if (message.authMode !== "") {
      writer.uint32(34).string(message.authMode);
    }
    if (message.providerConfigKey !== "") {
      writer.uint32(42).string(message.providerConfigKey);
    }
    if (message.provider !== "") {
      writer.uint32(50).string(message.provider);
    }
    if (message.environment !== "") {
      writer.uint32(58).string(message.environment);
    }
    if (message.success !== false) {
      writer.uint32(64).bool(message.success);
    }
    if (message.endUser !== undefined) {
      NangoConnectionWebhookEndUser.encode(message.endUser, writer.uint32(74).fork()).join();
    }
    if (message.error !== undefined) {
      NangoConnectionWebhookError.encode(message.error, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoConnectionWebhookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoConnectionWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.operation = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.connectionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.authMode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.providerConfigKey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.environment = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.endUser = NangoConnectionWebhookEndUser.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.error = NangoConnectionWebhookError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoConnectionWebhookRequest {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      operation: isSet(object.operation) ? globalThis.String(object.operation) : "",
      connectionId: isSet(object.connectionId) ? globalThis.String(object.connectionId) : "",
      authMode: isSet(object.authMode) ? globalThis.String(object.authMode) : "",
      providerConfigKey: isSet(object.providerConfigKey) ? globalThis.String(object.providerConfigKey) : "",
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      environment: isSet(object.environment) ? globalThis.String(object.environment) : "",
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      endUser: isSet(object.endUser) ? NangoConnectionWebhookEndUser.fromJSON(object.endUser) : undefined,
      error: isSet(object.error) ? NangoConnectionWebhookError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: NangoConnectionWebhookRequest): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.operation !== "") {
      obj.operation = message.operation;
    }
    if (message.connectionId !== "") {
      obj.connectionId = message.connectionId;
    }
    if (message.authMode !== "") {
      obj.authMode = message.authMode;
    }
    if (message.providerConfigKey !== "") {
      obj.providerConfigKey = message.providerConfigKey;
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.environment !== "") {
      obj.environment = message.environment;
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.endUser !== undefined) {
      obj.endUser = NangoConnectionWebhookEndUser.toJSON(message.endUser);
    }
    if (message.error !== undefined) {
      obj.error = NangoConnectionWebhookError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoConnectionWebhookRequest>, I>>(base?: I): NangoConnectionWebhookRequest {
    return NangoConnectionWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoConnectionWebhookRequest>, I>>(
    object: I,
  ): NangoConnectionWebhookRequest {
    const message = createBaseNangoConnectionWebhookRequest();
    message.type = object.type ?? "";
    message.operation = object.operation ?? "";
    message.connectionId = object.connectionId ?? "";
    message.authMode = object.authMode ?? "";
    message.providerConfigKey = object.providerConfigKey ?? "";
    message.provider = object.provider ?? "";
    message.environment = object.environment ?? "";
    message.success = object.success ?? false;
    message.endUser = (object.endUser !== undefined && object.endUser !== null)
      ? NangoConnectionWebhookEndUser.fromPartial(object.endUser)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? NangoConnectionWebhookError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseNangoSyncWebhookRequest(): NangoSyncWebhookRequest {
  return {
    type: "",
    connectionId: "",
    providerConfigKey: "",
    syncName: "",
    model: "",
    syncType: "",
    success: false,
    modifiedAfter: undefined,
    responseResults: undefined,
  };
}

export const NangoSyncWebhookRequest: MessageFns<NangoSyncWebhookRequest> = {
  encode(message: NangoSyncWebhookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.connectionId !== "") {
      writer.uint32(18).string(message.connectionId);
    }
    if (message.providerConfigKey !== "") {
      writer.uint32(26).string(message.providerConfigKey);
    }
    if (message.syncName !== "") {
      writer.uint32(34).string(message.syncName);
    }
    if (message.model !== "") {
      writer.uint32(42).string(message.model);
    }
    if (message.syncType !== "") {
      writer.uint32(50).string(message.syncType);
    }
    if (message.success !== false) {
      writer.uint32(56).bool(message.success);
    }
    if (message.modifiedAfter !== undefined) {
      Timestamp.encode(toTimestamp(message.modifiedAfter), writer.uint32(66).fork()).join();
    }
    if (message.responseResults !== undefined) {
      NangoSyncWebhookResponseResults.encode(message.responseResults, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoSyncWebhookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoSyncWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.connectionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.providerConfigKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.syncName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.model = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.syncType = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.modifiedAfter = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.responseResults = NangoSyncWebhookResponseResults.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoSyncWebhookRequest {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      connectionId: isSet(object.connectionId) ? globalThis.String(object.connectionId) : "",
      providerConfigKey: isSet(object.providerConfigKey) ? globalThis.String(object.providerConfigKey) : "",
      syncName: isSet(object.syncName) ? globalThis.String(object.syncName) : "",
      model: isSet(object.model) ? globalThis.String(object.model) : "",
      syncType: isSet(object.syncType) ? globalThis.String(object.syncType) : "",
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      modifiedAfter: isSet(object.modifiedAfter) ? fromJsonTimestamp(object.modifiedAfter) : undefined,
      responseResults: isSet(object.responseResults)
        ? NangoSyncWebhookResponseResults.fromJSON(object.responseResults)
        : undefined,
    };
  },

  toJSON(message: NangoSyncWebhookRequest): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.connectionId !== "") {
      obj.connectionId = message.connectionId;
    }
    if (message.providerConfigKey !== "") {
      obj.providerConfigKey = message.providerConfigKey;
    }
    if (message.syncName !== "") {
      obj.syncName = message.syncName;
    }
    if (message.model !== "") {
      obj.model = message.model;
    }
    if (message.syncType !== "") {
      obj.syncType = message.syncType;
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.modifiedAfter !== undefined) {
      obj.modifiedAfter = message.modifiedAfter.toISOString();
    }
    if (message.responseResults !== undefined) {
      obj.responseResults = NangoSyncWebhookResponseResults.toJSON(message.responseResults);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoSyncWebhookRequest>, I>>(base?: I): NangoSyncWebhookRequest {
    return NangoSyncWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoSyncWebhookRequest>, I>>(object: I): NangoSyncWebhookRequest {
    const message = createBaseNangoSyncWebhookRequest();
    message.type = object.type ?? "";
    message.connectionId = object.connectionId ?? "";
    message.providerConfigKey = object.providerConfigKey ?? "";
    message.syncName = object.syncName ?? "";
    message.model = object.model ?? "";
    message.syncType = object.syncType ?? "";
    message.success = object.success ?? false;
    message.modifiedAfter = object.modifiedAfter ?? undefined;
    message.responseResults = (object.responseResults !== undefined && object.responseResults !== null)
      ? NangoSyncWebhookResponseResults.fromPartial(object.responseResults)
      : undefined;
    return message;
  },
};

function createBaseNangoSyncWebhookResponseResults(): NangoSyncWebhookResponseResults {
  return { added: 0, updated: 0, deleted: 0 };
}

export const NangoSyncWebhookResponseResults: MessageFns<NangoSyncWebhookResponseResults> = {
  encode(message: NangoSyncWebhookResponseResults, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.added !== 0) {
      writer.uint32(8).int32(message.added);
    }
    if (message.updated !== 0) {
      writer.uint32(16).int32(message.updated);
    }
    if (message.deleted !== 0) {
      writer.uint32(24).int32(message.deleted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoSyncWebhookResponseResults {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoSyncWebhookResponseResults();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.added = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.updated = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.deleted = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoSyncWebhookResponseResults {
    return {
      added: isSet(object.added) ? globalThis.Number(object.added) : 0,
      updated: isSet(object.updated) ? globalThis.Number(object.updated) : 0,
      deleted: isSet(object.deleted) ? globalThis.Number(object.deleted) : 0,
    };
  },

  toJSON(message: NangoSyncWebhookResponseResults): unknown {
    const obj: any = {};
    if (message.added !== 0) {
      obj.added = Math.round(message.added);
    }
    if (message.updated !== 0) {
      obj.updated = Math.round(message.updated);
    }
    if (message.deleted !== 0) {
      obj.deleted = Math.round(message.deleted);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoSyncWebhookResponseResults>, I>>(base?: I): NangoSyncWebhookResponseResults {
    return NangoSyncWebhookResponseResults.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoSyncWebhookResponseResults>, I>>(
    object: I,
  ): NangoSyncWebhookResponseResults {
    const message = createBaseNangoSyncWebhookResponseResults();
    message.added = object.added ?? 0;
    message.updated = object.updated ?? 0;
    message.deleted = object.deleted ?? 0;
    return message;
  },
};

function createBaseNangoTriggerSyncRequest(): NangoTriggerSyncRequest {
  return { providerConfigKey: "", syncs: [], connectionId: "", syncMode: 0, userId: "" };
}

export const NangoTriggerSyncRequest: MessageFns<NangoTriggerSyncRequest> = {
  encode(message: NangoTriggerSyncRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerConfigKey !== "") {
      writer.uint32(10).string(message.providerConfigKey);
    }
    for (const v of message.syncs) {
      writer.uint32(18).string(v!);
    }
    if (message.connectionId !== "") {
      writer.uint32(26).string(message.connectionId);
    }
    if (message.syncMode !== 0) {
      writer.uint32(32).int32(message.syncMode);
    }
    if (message.userId !== "") {
      writer.uint32(42).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoTriggerSyncRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoTriggerSyncRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerConfigKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.syncs.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.connectionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.syncMode = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoTriggerSyncRequest {
    return {
      providerConfigKey: isSet(object.providerConfigKey) ? globalThis.String(object.providerConfigKey) : "",
      syncs: globalThis.Array.isArray(object?.syncs) ? object.syncs.map((e: any) => globalThis.String(e)) : [],
      connectionId: isSet(object.connectionId) ? globalThis.String(object.connectionId) : "",
      syncMode: isSet(object.syncMode) ? syncModeFromJSON(object.syncMode) : 0,
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
    };
  },

  toJSON(message: NangoTriggerSyncRequest): unknown {
    const obj: any = {};
    if (message.providerConfigKey !== "") {
      obj.providerConfigKey = message.providerConfigKey;
    }
    if (message.syncs?.length) {
      obj.syncs = message.syncs;
    }
    if (message.connectionId !== "") {
      obj.connectionId = message.connectionId;
    }
    if (message.syncMode !== 0) {
      obj.syncMode = syncModeToJSON(message.syncMode);
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoTriggerSyncRequest>, I>>(base?: I): NangoTriggerSyncRequest {
    return NangoTriggerSyncRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoTriggerSyncRequest>, I>>(object: I): NangoTriggerSyncRequest {
    const message = createBaseNangoTriggerSyncRequest();
    message.providerConfigKey = object.providerConfigKey ?? "";
    message.syncs = object.syncs?.map((e) => e) || [];
    message.connectionId = object.connectionId ?? "";
    message.syncMode = object.syncMode ?? 0;
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseNangoTriggerSyncResponse(): NangoTriggerSyncResponse {
  return { error: 0, message: "" };
}

export const NangoTriggerSyncResponse: MessageFns<NangoTriggerSyncResponse> = {
  encode(message: NangoTriggerSyncResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== 0) {
      writer.uint32(8).int32(message.error);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoTriggerSyncResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoTriggerSyncResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.error = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoTriggerSyncResponse {
    return {
      error: isSet(object.error) ? semurEngineErrorCodeFromJSON(object.error) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: NangoTriggerSyncResponse): unknown {
    const obj: any = {};
    if (message.error !== 0) {
      obj.error = semurEngineErrorCodeToJSON(message.error);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoTriggerSyncResponse>, I>>(base?: I): NangoTriggerSyncResponse {
    return NangoTriggerSyncResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoTriggerSyncResponse>, I>>(object: I): NangoTriggerSyncResponse {
    const message = createBaseNangoTriggerSyncResponse();
    message.error = object.error ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
