// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: external_apps/external_app.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "external_apps";

export enum ExternalAppType {
  TELEGRAM_BOT = 0,
  UNRECOGNIZED = -1,
}

export function externalAppTypeFromJSON(object: any): ExternalAppType {
  switch (object) {
    case 0:
    case "TELEGRAM_BOT":
      return ExternalAppType.TELEGRAM_BOT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ExternalAppType.UNRECOGNIZED;
  }
}

export function externalAppTypeToJSON(object: ExternalAppType): string {
  switch (object) {
    case ExternalAppType.TELEGRAM_BOT:
      return "TELEGRAM_BOT";
    case ExternalAppType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ExternalAppIntegrationStatus {
  INACTIVE = 0,
  ACTIVE = 1,
  DELETED = 2,
  UNRECOGNIZED = -1,
}

export function externalAppIntegrationStatusFromJSON(object: any): ExternalAppIntegrationStatus {
  switch (object) {
    case 0:
    case "INACTIVE":
      return ExternalAppIntegrationStatus.INACTIVE;
    case 1:
    case "ACTIVE":
      return ExternalAppIntegrationStatus.ACTIVE;
    case 2:
    case "DELETED":
      return ExternalAppIntegrationStatus.DELETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ExternalAppIntegrationStatus.UNRECOGNIZED;
  }
}

export function externalAppIntegrationStatusToJSON(object: ExternalAppIntegrationStatus): string {
  switch (object) {
    case ExternalAppIntegrationStatus.INACTIVE:
      return "INACTIVE";
    case ExternalAppIntegrationStatus.ACTIVE:
      return "ACTIVE";
    case ExternalAppIntegrationStatus.DELETED:
      return "DELETED";
    case ExternalAppIntegrationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ExternalAppIntegration {
  id: string;
  userId: string;
  type: ExternalAppType;
  metadata: { [key: string]: string };
  status: ExternalAppIntegrationStatus;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface ExternalAppIntegration_MetadataEntry {
  key: string;
  value: string;
}

function createBaseExternalAppIntegration(): ExternalAppIntegration {
  return { id: "", userId: "", type: 0, metadata: {}, status: 0, createdAt: undefined, updatedAt: undefined };
}

export const ExternalAppIntegration: MessageFns<ExternalAppIntegration> = {
  encode(message: ExternalAppIntegration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      ExternalAppIntegration_MetadataEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(50).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExternalAppIntegration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExternalAppIntegration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = ExternalAppIntegration_MetadataEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.metadata[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExternalAppIntegration {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      type: isSet(object.type) ? externalAppTypeFromJSON(object.type) : 0,
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      status: isSet(object.status) ? externalAppIntegrationStatusFromJSON(object.status) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: ExternalAppIntegration): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.type !== 0) {
      obj.type = externalAppTypeToJSON(message.type);
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata);
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    if (message.status !== 0) {
      obj.status = externalAppIntegrationStatusToJSON(message.status);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExternalAppIntegration>, I>>(base?: I): ExternalAppIntegration {
    return ExternalAppIntegration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExternalAppIntegration>, I>>(object: I): ExternalAppIntegration {
    const message = createBaseExternalAppIntegration();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.type = object.type ?? 0;
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.status = object.status ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseExternalAppIntegration_MetadataEntry(): ExternalAppIntegration_MetadataEntry {
  return { key: "", value: "" };
}

export const ExternalAppIntegration_MetadataEntry: MessageFns<ExternalAppIntegration_MetadataEntry> = {
  encode(message: ExternalAppIntegration_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExternalAppIntegration_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExternalAppIntegration_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExternalAppIntegration_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ExternalAppIntegration_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExternalAppIntegration_MetadataEntry>, I>>(
    base?: I,
  ): ExternalAppIntegration_MetadataEntry {
    return ExternalAppIntegration_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExternalAppIntegration_MetadataEntry>, I>>(
    object: I,
  ): ExternalAppIntegration_MetadataEntry {
    const message = createBaseExternalAppIntegration_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
