// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: external_apps/telegram_bot_integration.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "external_apps";

export enum TelegramBotIntegrationStatus {
  TELEGRAM_BOT_INACTIVE = 0,
  TELEGRAM_BOT_ACTIVE = 1,
  TELEGRAM_BOT_DELETED = 2,
  UNRECOGNIZED = -1,
}

export function telegramBotIntegrationStatusFromJSON(object: any): TelegramBotIntegrationStatus {
  switch (object) {
    case 0:
    case "TELEGRAM_BOT_INACTIVE":
      return TelegramBotIntegrationStatus.TELEGRAM_BOT_INACTIVE;
    case 1:
    case "TELEGRAM_BOT_ACTIVE":
      return TelegramBotIntegrationStatus.TELEGRAM_BOT_ACTIVE;
    case 2:
    case "TELEGRAM_BOT_DELETED":
      return TelegramBotIntegrationStatus.TELEGRAM_BOT_DELETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TelegramBotIntegrationStatus.UNRECOGNIZED;
  }
}

export function telegramBotIntegrationStatusToJSON(object: TelegramBotIntegrationStatus): string {
  switch (object) {
    case TelegramBotIntegrationStatus.TELEGRAM_BOT_INACTIVE:
      return "TELEGRAM_BOT_INACTIVE";
    case TelegramBotIntegrationStatus.TELEGRAM_BOT_ACTIVE:
      return "TELEGRAM_BOT_ACTIVE";
    case TelegramBotIntegrationStatus.TELEGRAM_BOT_DELETED:
      return "TELEGRAM_BOT_DELETED";
    case TelegramBotIntegrationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface TelegramBotIntegration {
  id: string;
  username: string;
  userId: string;
  userFirstName: string;
  userLastName: string;
  integrationStatus: TelegramBotIntegrationStatus;
  createdAt: Date | undefined;
}

function createBaseTelegramBotIntegration(): TelegramBotIntegration {
  return {
    id: "",
    username: "",
    userId: "",
    userFirstName: "",
    userLastName: "",
    integrationStatus: 0,
    createdAt: undefined,
  };
}

export const TelegramBotIntegration: MessageFns<TelegramBotIntegration> = {
  encode(message: TelegramBotIntegration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.userFirstName !== "") {
      writer.uint32(34).string(message.userFirstName);
    }
    if (message.userLastName !== "") {
      writer.uint32(42).string(message.userLastName);
    }
    if (message.integrationStatus !== 0) {
      writer.uint32(48).int32(message.integrationStatus);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TelegramBotIntegration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTelegramBotIntegration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userFirstName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.userLastName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.integrationStatus = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TelegramBotIntegration {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      userFirstName: isSet(object.userFirstName) ? globalThis.String(object.userFirstName) : "",
      userLastName: isSet(object.userLastName) ? globalThis.String(object.userLastName) : "",
      integrationStatus: isSet(object.integrationStatus)
        ? telegramBotIntegrationStatusFromJSON(object.integrationStatus)
        : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
    };
  },

  toJSON(message: TelegramBotIntegration): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.userFirstName !== "") {
      obj.userFirstName = message.userFirstName;
    }
    if (message.userLastName !== "") {
      obj.userLastName = message.userLastName;
    }
    if (message.integrationStatus !== 0) {
      obj.integrationStatus = telegramBotIntegrationStatusToJSON(message.integrationStatus);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TelegramBotIntegration>, I>>(base?: I): TelegramBotIntegration {
    return TelegramBotIntegration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TelegramBotIntegration>, I>>(object: I): TelegramBotIntegration {
    const message = createBaseTelegramBotIntegration();
    message.id = object.id ?? "";
    message.username = object.username ?? "";
    message.userId = object.userId ?? "";
    message.userFirstName = object.userFirstName ?? "";
    message.userLastName = object.userLastName ?? "";
    message.integrationStatus = object.integrationStatus ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
