// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: nango/nango.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AgentCategory, agentCategoryFromJSON, agentCategoryToJSON } from "../agents/agent";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "nango";

export enum NangoIntegrationStatus {
  INACTIVE = 0,
  ACTIVE = 1,
  UNRECOGNIZED = -1,
}

export function nangoIntegrationStatusFromJSON(object: any): NangoIntegrationStatus {
  switch (object) {
    case 0:
    case "INACTIVE":
      return NangoIntegrationStatus.INACTIVE;
    case 1:
    case "ACTIVE":
      return NangoIntegrationStatus.ACTIVE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NangoIntegrationStatus.UNRECOGNIZED;
  }
}

export function nangoIntegrationStatusToJSON(object: NangoIntegrationStatus): string {
  switch (object) {
    case NangoIntegrationStatus.INACTIVE:
      return "INACTIVE";
    case NangoIntegrationStatus.ACTIVE:
      return "ACTIVE";
    case NangoIntegrationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum NangoConnectionStatus {
  NANGO_CONNECTION_INACTIVE = 0,
  NANGO_CONNECTION_ACTIVE = 1,
  NANGO_CONNECTION_CONNECTING = 2,
  UNRECOGNIZED = -1,
}

export function nangoConnectionStatusFromJSON(object: any): NangoConnectionStatus {
  switch (object) {
    case 0:
    case "NANGO_CONNECTION_INACTIVE":
      return NangoConnectionStatus.NANGO_CONNECTION_INACTIVE;
    case 1:
    case "NANGO_CONNECTION_ACTIVE":
      return NangoConnectionStatus.NANGO_CONNECTION_ACTIVE;
    case 2:
    case "NANGO_CONNECTION_CONNECTING":
      return NangoConnectionStatus.NANGO_CONNECTION_CONNECTING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NangoConnectionStatus.UNRECOGNIZED;
  }
}

export function nangoConnectionStatusToJSON(object: NangoConnectionStatus): string {
  switch (object) {
    case NangoConnectionStatus.NANGO_CONNECTION_INACTIVE:
      return "NANGO_CONNECTION_INACTIVE";
    case NangoConnectionStatus.NANGO_CONNECTION_ACTIVE:
      return "NANGO_CONNECTION_ACTIVE";
    case NangoConnectionStatus.NANGO_CONNECTION_CONNECTING:
      return "NANGO_CONNECTION_CONNECTING";
    case NangoConnectionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface NangoIntegration {
  id: string;
  name: string;
  status: NangoIntegrationStatus;
  categories: AgentCategory[];
}

export interface NangoConnectionError {
  type: string;
  message: string;
}

export interface NangoConnection {
  /** Represents nango integration id */
  id: string;
  userId: string;
  connectionId: string;
  organizationId?: string | undefined;
  status: NangoConnectionStatus;
  provider?: string | undefined;
  authMode?: string | undefined;
  nangoError?: NangoConnectionError | undefined;
  updatedAt: Date | undefined;
}

export interface NangoConnectionPublic {
  /** Represents nango integration id */
  id: string;
  userId: string;
  organizationId?: string | undefined;
  status: NangoConnectionStatus;
  provider?: string | undefined;
  updatedAt: Date | undefined;
}

function createBaseNangoIntegration(): NangoIntegration {
  return { id: "", name: "", status: 0, categories: [] };
}

export const NangoIntegration: MessageFns<NangoIntegration> = {
  encode(message: NangoIntegration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.status !== 0) {
      writer.uint32(24).int32(message.status);
    }
    writer.uint32(34).fork();
    for (const v of message.categories) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoIntegration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoIntegration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.categories.push(reader.int32() as any);

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.categories.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoIntegration {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      status: isSet(object.status) ? nangoIntegrationStatusFromJSON(object.status) : 0,
      categories: globalThis.Array.isArray(object?.categories)
        ? object.categories.map((e: any) => agentCategoryFromJSON(e))
        : [],
    };
  },

  toJSON(message: NangoIntegration): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.status !== 0) {
      obj.status = nangoIntegrationStatusToJSON(message.status);
    }
    if (message.categories?.length) {
      obj.categories = message.categories.map((e) => agentCategoryToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoIntegration>, I>>(base?: I): NangoIntegration {
    return NangoIntegration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoIntegration>, I>>(object: I): NangoIntegration {
    const message = createBaseNangoIntegration();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.status = object.status ?? 0;
    message.categories = object.categories?.map((e) => e) || [];
    return message;
  },
};

function createBaseNangoConnectionError(): NangoConnectionError {
  return { type: "", message: "" };
}

export const NangoConnectionError: MessageFns<NangoConnectionError> = {
  encode(message: NangoConnectionError, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoConnectionError {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoConnectionError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoConnectionError {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: NangoConnectionError): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoConnectionError>, I>>(base?: I): NangoConnectionError {
    return NangoConnectionError.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoConnectionError>, I>>(object: I): NangoConnectionError {
    const message = createBaseNangoConnectionError();
    message.type = object.type ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseNangoConnection(): NangoConnection {
  return {
    id: "",
    userId: "",
    connectionId: "",
    organizationId: undefined,
    status: 0,
    provider: undefined,
    authMode: undefined,
    nangoError: undefined,
    updatedAt: undefined,
  };
}

export const NangoConnection: MessageFns<NangoConnection> = {
  encode(message: NangoConnection, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.connectionId !== "") {
      writer.uint32(26).string(message.connectionId);
    }
    if (message.organizationId !== undefined) {
      writer.uint32(34).string(message.organizationId);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.provider !== undefined) {
      writer.uint32(50).string(message.provider);
    }
    if (message.authMode !== undefined) {
      writer.uint32(58).string(message.authMode);
    }
    if (message.nangoError !== undefined) {
      NangoConnectionError.encode(message.nangoError, writer.uint32(66).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoConnection {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoConnection();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.connectionId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.organizationId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.authMode = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.nangoError = NangoConnectionError.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoConnection {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      connectionId: isSet(object.connectionId) ? globalThis.String(object.connectionId) : "",
      organizationId: isSet(object.organizationId) ? globalThis.String(object.organizationId) : undefined,
      status: isSet(object.status) ? nangoConnectionStatusFromJSON(object.status) : 0,
      provider: isSet(object.provider) ? globalThis.String(object.provider) : undefined,
      authMode: isSet(object.authMode) ? globalThis.String(object.authMode) : undefined,
      nangoError: isSet(object.nangoError) ? NangoConnectionError.fromJSON(object.nangoError) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: NangoConnection): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.connectionId !== "") {
      obj.connectionId = message.connectionId;
    }
    if (message.organizationId !== undefined) {
      obj.organizationId = message.organizationId;
    }
    if (message.status !== 0) {
      obj.status = nangoConnectionStatusToJSON(message.status);
    }
    if (message.provider !== undefined) {
      obj.provider = message.provider;
    }
    if (message.authMode !== undefined) {
      obj.authMode = message.authMode;
    }
    if (message.nangoError !== undefined) {
      obj.nangoError = NangoConnectionError.toJSON(message.nangoError);
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoConnection>, I>>(base?: I): NangoConnection {
    return NangoConnection.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoConnection>, I>>(object: I): NangoConnection {
    const message = createBaseNangoConnection();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.connectionId = object.connectionId ?? "";
    message.organizationId = object.organizationId ?? undefined;
    message.status = object.status ?? 0;
    message.provider = object.provider ?? undefined;
    message.authMode = object.authMode ?? undefined;
    message.nangoError = (object.nangoError !== undefined && object.nangoError !== null)
      ? NangoConnectionError.fromPartial(object.nangoError)
      : undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseNangoConnectionPublic(): NangoConnectionPublic {
  return { id: "", userId: "", organizationId: undefined, status: 0, provider: undefined, updatedAt: undefined };
}

export const NangoConnectionPublic: MessageFns<NangoConnectionPublic> = {
  encode(message: NangoConnectionPublic, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.organizationId !== undefined) {
      writer.uint32(26).string(message.organizationId);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    if (message.provider !== undefined) {
      writer.uint32(42).string(message.provider);
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NangoConnectionPublic {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNangoConnectionPublic();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.organizationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NangoConnectionPublic {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      organizationId: isSet(object.organizationId) ? globalThis.String(object.organizationId) : undefined,
      status: isSet(object.status) ? nangoConnectionStatusFromJSON(object.status) : 0,
      provider: isSet(object.provider) ? globalThis.String(object.provider) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: NangoConnectionPublic): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.organizationId !== undefined) {
      obj.organizationId = message.organizationId;
    }
    if (message.status !== 0) {
      obj.status = nangoConnectionStatusToJSON(message.status);
    }
    if (message.provider !== undefined) {
      obj.provider = message.provider;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NangoConnectionPublic>, I>>(base?: I): NangoConnectionPublic {
    return NangoConnectionPublic.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NangoConnectionPublic>, I>>(object: I): NangoConnectionPublic {
    const message = createBaseNangoConnectionPublic();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.organizationId = object.organizationId ?? undefined;
    message.status = object.status ?? 0;
    message.provider = object.provider ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
