// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: syncs/sync_google-calendar.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { SyncNangoMetadata } from "./sync";

export const protobufPackage = "syncs";

export interface SyncGoogleCalendarEvent {
  id: string;
  kind: string;
  etag: string;
  status: string;
  htmlLink: string;
  created: Date | undefined;
  updated: Date | undefined;
  summary: string;
  description: string;
  fullContent: string;
  location?: string | undefined;
  creator?: SyncGoogleCalendarEventCreator | undefined;
  organizer?: SyncGoogleCalendarEventOrganizer | undefined;
  start: Date | undefined;
  end: Date | undefined;
  endTimeUnspecified?: boolean | undefined;
  recurrence: string[];
  recurringEventId?: string | undefined;
  attendees: SyncGoogleCalendarEventAttendee[];
  attendeesOmitted?: boolean | undefined;
  hangoutLink?: string | undefined;
  nangoMetadata: SyncNangoMetadata | undefined;
}

export interface SyncGoogleCalendarEventCreator {
  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  self?: boolean | undefined;
}

export interface SyncGoogleCalendarEventOrganizer {
  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  self?: boolean | undefined;
}

export interface SyncGoogleCalendarEventAttendee {
  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  organizer?: boolean | undefined;
  self?: boolean | undefined;
  resource?: boolean | undefined;
  optional?: boolean | undefined;
  responseStatus?: string | undefined;
  comment?: string | undefined;
  additionalGuests?: number | undefined;
}

function createBaseSyncGoogleCalendarEvent(): SyncGoogleCalendarEvent {
  return {
    id: "",
    kind: "",
    etag: "",
    status: "",
    htmlLink: "",
    created: undefined,
    updated: undefined,
    summary: "",
    description: "",
    fullContent: "",
    location: undefined,
    creator: undefined,
    organizer: undefined,
    start: undefined,
    end: undefined,
    endTimeUnspecified: undefined,
    recurrence: [],
    recurringEventId: undefined,
    attendees: [],
    attendeesOmitted: undefined,
    hangoutLink: undefined,
    nangoMetadata: undefined,
  };
}

export const SyncGoogleCalendarEvent: MessageFns<SyncGoogleCalendarEvent> = {
  encode(message: SyncGoogleCalendarEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.kind !== "") {
      writer.uint32(18).string(message.kind);
    }
    if (message.etag !== "") {
      writer.uint32(26).string(message.etag);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    if (message.htmlLink !== "") {
      writer.uint32(42).string(message.htmlLink);
    }
    if (message.created !== undefined) {
      Timestamp.encode(toTimestamp(message.created), writer.uint32(50).fork()).join();
    }
    if (message.updated !== undefined) {
      Timestamp.encode(toTimestamp(message.updated), writer.uint32(58).fork()).join();
    }
    if (message.summary !== "") {
      writer.uint32(66).string(message.summary);
    }
    if (message.description !== "") {
      writer.uint32(74).string(message.description);
    }
    if (message.fullContent !== "") {
      writer.uint32(82).string(message.fullContent);
    }
    if (message.location !== undefined) {
      writer.uint32(90).string(message.location);
    }
    if (message.creator !== undefined) {
      SyncGoogleCalendarEventCreator.encode(message.creator, writer.uint32(98).fork()).join();
    }
    if (message.organizer !== undefined) {
      SyncGoogleCalendarEventOrganizer.encode(message.organizer, writer.uint32(106).fork()).join();
    }
    if (message.start !== undefined) {
      Timestamp.encode(toTimestamp(message.start), writer.uint32(114).fork()).join();
    }
    if (message.end !== undefined) {
      Timestamp.encode(toTimestamp(message.end), writer.uint32(122).fork()).join();
    }
    if (message.endTimeUnspecified !== undefined) {
      writer.uint32(128).bool(message.endTimeUnspecified);
    }
    for (const v of message.recurrence) {
      writer.uint32(138).string(v!);
    }
    if (message.recurringEventId !== undefined) {
      writer.uint32(146).string(message.recurringEventId);
    }
    for (const v of message.attendees) {
      SyncGoogleCalendarEventAttendee.encode(v!, writer.uint32(154).fork()).join();
    }
    if (message.attendeesOmitted !== undefined) {
      writer.uint32(160).bool(message.attendeesOmitted);
    }
    if (message.hangoutLink !== undefined) {
      writer.uint32(170).string(message.hangoutLink);
    }
    if (message.nangoMetadata !== undefined) {
      SyncNangoMetadata.encode(message.nangoMetadata, writer.uint32(178).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleCalendarEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleCalendarEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.kind = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.etag = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.htmlLink = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.created = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updated = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.fullContent = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.creator = SyncGoogleCalendarEventCreator.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.organizer = SyncGoogleCalendarEventOrganizer.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.start = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.end = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.endTimeUnspecified = reader.bool();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.recurrence.push(reader.string());
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.recurringEventId = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.attendees.push(SyncGoogleCalendarEventAttendee.decode(reader, reader.uint32()));
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.attendeesOmitted = reader.bool();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.hangoutLink = reader.string();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.nangoMetadata = SyncNangoMetadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleCalendarEvent {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
      etag: isSet(object.etag) ? globalThis.String(object.etag) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      htmlLink: isSet(object.htmlLink) ? globalThis.String(object.htmlLink) : "",
      created: isSet(object.created) ? fromJsonTimestamp(object.created) : undefined,
      updated: isSet(object.updated) ? fromJsonTimestamp(object.updated) : undefined,
      summary: isSet(object.summary) ? globalThis.String(object.summary) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      fullContent: isSet(object.fullContent) ? globalThis.String(object.fullContent) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : undefined,
      creator: isSet(object.creator) ? SyncGoogleCalendarEventCreator.fromJSON(object.creator) : undefined,
      organizer: isSet(object.organizer) ? SyncGoogleCalendarEventOrganizer.fromJSON(object.organizer) : undefined,
      start: isSet(object.start) ? fromJsonTimestamp(object.start) : undefined,
      end: isSet(object.end) ? fromJsonTimestamp(object.end) : undefined,
      endTimeUnspecified: isSet(object.endTimeUnspecified) ? globalThis.Boolean(object.endTimeUnspecified) : undefined,
      recurrence: globalThis.Array.isArray(object?.recurrence)
        ? object.recurrence.map((e: any) => globalThis.String(e))
        : [],
      recurringEventId: isSet(object.recurringEventId) ? globalThis.String(object.recurringEventId) : undefined,
      attendees: globalThis.Array.isArray(object?.attendees)
        ? object.attendees.map((e: any) => SyncGoogleCalendarEventAttendee.fromJSON(e))
        : [],
      attendeesOmitted: isSet(object.attendeesOmitted) ? globalThis.Boolean(object.attendeesOmitted) : undefined,
      hangoutLink: isSet(object.hangoutLink) ? globalThis.String(object.hangoutLink) : undefined,
      nangoMetadata: isSet(object.nangoMetadata) ? SyncNangoMetadata.fromJSON(object.nangoMetadata) : undefined,
    };
  },

  toJSON(message: SyncGoogleCalendarEvent): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    if (message.etag !== "") {
      obj.etag = message.etag;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.htmlLink !== "") {
      obj.htmlLink = message.htmlLink;
    }
    if (message.created !== undefined) {
      obj.created = message.created.toISOString();
    }
    if (message.updated !== undefined) {
      obj.updated = message.updated.toISOString();
    }
    if (message.summary !== "") {
      obj.summary = message.summary;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.fullContent !== "") {
      obj.fullContent = message.fullContent;
    }
    if (message.location !== undefined) {
      obj.location = message.location;
    }
    if (message.creator !== undefined) {
      obj.creator = SyncGoogleCalendarEventCreator.toJSON(message.creator);
    }
    if (message.organizer !== undefined) {
      obj.organizer = SyncGoogleCalendarEventOrganizer.toJSON(message.organizer);
    }
    if (message.start !== undefined) {
      obj.start = message.start.toISOString();
    }
    if (message.end !== undefined) {
      obj.end = message.end.toISOString();
    }
    if (message.endTimeUnspecified !== undefined) {
      obj.endTimeUnspecified = message.endTimeUnspecified;
    }
    if (message.recurrence?.length) {
      obj.recurrence = message.recurrence;
    }
    if (message.recurringEventId !== undefined) {
      obj.recurringEventId = message.recurringEventId;
    }
    if (message.attendees?.length) {
      obj.attendees = message.attendees.map((e) => SyncGoogleCalendarEventAttendee.toJSON(e));
    }
    if (message.attendeesOmitted !== undefined) {
      obj.attendeesOmitted = message.attendeesOmitted;
    }
    if (message.hangoutLink !== undefined) {
      obj.hangoutLink = message.hangoutLink;
    }
    if (message.nangoMetadata !== undefined) {
      obj.nangoMetadata = SyncNangoMetadata.toJSON(message.nangoMetadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleCalendarEvent>, I>>(base?: I): SyncGoogleCalendarEvent {
    return SyncGoogleCalendarEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleCalendarEvent>, I>>(object: I): SyncGoogleCalendarEvent {
    const message = createBaseSyncGoogleCalendarEvent();
    message.id = object.id ?? "";
    message.kind = object.kind ?? "";
    message.etag = object.etag ?? "";
    message.status = object.status ?? "";
    message.htmlLink = object.htmlLink ?? "";
    message.created = object.created ?? undefined;
    message.updated = object.updated ?? undefined;
    message.summary = object.summary ?? "";
    message.description = object.description ?? "";
    message.fullContent = object.fullContent ?? "";
    message.location = object.location ?? undefined;
    message.creator = (object.creator !== undefined && object.creator !== null)
      ? SyncGoogleCalendarEventCreator.fromPartial(object.creator)
      : undefined;
    message.organizer = (object.organizer !== undefined && object.organizer !== null)
      ? SyncGoogleCalendarEventOrganizer.fromPartial(object.organizer)
      : undefined;
    message.start = object.start ?? undefined;
    message.end = object.end ?? undefined;
    message.endTimeUnspecified = object.endTimeUnspecified ?? undefined;
    message.recurrence = object.recurrence?.map((e) => e) || [];
    message.recurringEventId = object.recurringEventId ?? undefined;
    message.attendees = object.attendees?.map((e) => SyncGoogleCalendarEventAttendee.fromPartial(e)) || [];
    message.attendeesOmitted = object.attendeesOmitted ?? undefined;
    message.hangoutLink = object.hangoutLink ?? undefined;
    message.nangoMetadata = (object.nangoMetadata !== undefined && object.nangoMetadata !== null)
      ? SyncNangoMetadata.fromPartial(object.nangoMetadata)
      : undefined;
    return message;
  },
};

function createBaseSyncGoogleCalendarEventCreator(): SyncGoogleCalendarEventCreator {
  return { id: undefined, email: undefined, displayName: undefined, self: undefined };
}

export const SyncGoogleCalendarEventCreator: MessageFns<SyncGoogleCalendarEventCreator> = {
  encode(message: SyncGoogleCalendarEventCreator, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== undefined) {
      writer.uint32(18).string(message.email);
    }
    if (message.displayName !== undefined) {
      writer.uint32(26).string(message.displayName);
    }
    if (message.self !== undefined) {
      writer.uint32(32).bool(message.self);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleCalendarEventCreator {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleCalendarEventCreator();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.self = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleCalendarEventCreator {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : undefined,
      self: isSet(object.self) ? globalThis.Boolean(object.self) : undefined,
    };
  },

  toJSON(message: SyncGoogleCalendarEventCreator): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.displayName !== undefined) {
      obj.displayName = message.displayName;
    }
    if (message.self !== undefined) {
      obj.self = message.self;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleCalendarEventCreator>, I>>(base?: I): SyncGoogleCalendarEventCreator {
    return SyncGoogleCalendarEventCreator.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleCalendarEventCreator>, I>>(
    object: I,
  ): SyncGoogleCalendarEventCreator {
    const message = createBaseSyncGoogleCalendarEventCreator();
    message.id = object.id ?? undefined;
    message.email = object.email ?? undefined;
    message.displayName = object.displayName ?? undefined;
    message.self = object.self ?? undefined;
    return message;
  },
};

function createBaseSyncGoogleCalendarEventOrganizer(): SyncGoogleCalendarEventOrganizer {
  return { id: undefined, email: undefined, displayName: undefined, self: undefined };
}

export const SyncGoogleCalendarEventOrganizer: MessageFns<SyncGoogleCalendarEventOrganizer> = {
  encode(message: SyncGoogleCalendarEventOrganizer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== undefined) {
      writer.uint32(18).string(message.email);
    }
    if (message.displayName !== undefined) {
      writer.uint32(26).string(message.displayName);
    }
    if (message.self !== undefined) {
      writer.uint32(32).bool(message.self);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleCalendarEventOrganizer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleCalendarEventOrganizer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.self = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleCalendarEventOrganizer {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : undefined,
      self: isSet(object.self) ? globalThis.Boolean(object.self) : undefined,
    };
  },

  toJSON(message: SyncGoogleCalendarEventOrganizer): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.displayName !== undefined) {
      obj.displayName = message.displayName;
    }
    if (message.self !== undefined) {
      obj.self = message.self;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleCalendarEventOrganizer>, I>>(
    base?: I,
  ): SyncGoogleCalendarEventOrganizer {
    return SyncGoogleCalendarEventOrganizer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleCalendarEventOrganizer>, I>>(
    object: I,
  ): SyncGoogleCalendarEventOrganizer {
    const message = createBaseSyncGoogleCalendarEventOrganizer();
    message.id = object.id ?? undefined;
    message.email = object.email ?? undefined;
    message.displayName = object.displayName ?? undefined;
    message.self = object.self ?? undefined;
    return message;
  },
};

function createBaseSyncGoogleCalendarEventAttendee(): SyncGoogleCalendarEventAttendee {
  return {
    id: undefined,
    email: undefined,
    displayName: undefined,
    organizer: undefined,
    self: undefined,
    resource: undefined,
    optional: undefined,
    responseStatus: undefined,
    comment: undefined,
    additionalGuests: undefined,
  };
}

export const SyncGoogleCalendarEventAttendee: MessageFns<SyncGoogleCalendarEventAttendee> = {
  encode(message: SyncGoogleCalendarEventAttendee, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== undefined) {
      writer.uint32(18).string(message.email);
    }
    if (message.displayName !== undefined) {
      writer.uint32(26).string(message.displayName);
    }
    if (message.organizer !== undefined) {
      writer.uint32(32).bool(message.organizer);
    }
    if (message.self !== undefined) {
      writer.uint32(40).bool(message.self);
    }
    if (message.resource !== undefined) {
      writer.uint32(48).bool(message.resource);
    }
    if (message.optional !== undefined) {
      writer.uint32(56).bool(message.optional);
    }
    if (message.responseStatus !== undefined) {
      writer.uint32(66).string(message.responseStatus);
    }
    if (message.comment !== undefined) {
      writer.uint32(74).string(message.comment);
    }
    if (message.additionalGuests !== undefined) {
      writer.uint32(80).int32(message.additionalGuests);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleCalendarEventAttendee {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleCalendarEventAttendee();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.organizer = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.self = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.resource = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.optional = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.responseStatus = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.comment = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.additionalGuests = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleCalendarEventAttendee {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : undefined,
      organizer: isSet(object.organizer) ? globalThis.Boolean(object.organizer) : undefined,
      self: isSet(object.self) ? globalThis.Boolean(object.self) : undefined,
      resource: isSet(object.resource) ? globalThis.Boolean(object.resource) : undefined,
      optional: isSet(object.optional) ? globalThis.Boolean(object.optional) : undefined,
      responseStatus: isSet(object.responseStatus) ? globalThis.String(object.responseStatus) : undefined,
      comment: isSet(object.comment) ? globalThis.String(object.comment) : undefined,
      additionalGuests: isSet(object.additionalGuests) ? globalThis.Number(object.additionalGuests) : undefined,
    };
  },

  toJSON(message: SyncGoogleCalendarEventAttendee): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.displayName !== undefined) {
      obj.displayName = message.displayName;
    }
    if (message.organizer !== undefined) {
      obj.organizer = message.organizer;
    }
    if (message.self !== undefined) {
      obj.self = message.self;
    }
    if (message.resource !== undefined) {
      obj.resource = message.resource;
    }
    if (message.optional !== undefined) {
      obj.optional = message.optional;
    }
    if (message.responseStatus !== undefined) {
      obj.responseStatus = message.responseStatus;
    }
    if (message.comment !== undefined) {
      obj.comment = message.comment;
    }
    if (message.additionalGuests !== undefined) {
      obj.additionalGuests = Math.round(message.additionalGuests);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleCalendarEventAttendee>, I>>(base?: I): SyncGoogleCalendarEventAttendee {
    return SyncGoogleCalendarEventAttendee.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleCalendarEventAttendee>, I>>(
    object: I,
  ): SyncGoogleCalendarEventAttendee {
    const message = createBaseSyncGoogleCalendarEventAttendee();
    message.id = object.id ?? undefined;
    message.email = object.email ?? undefined;
    message.displayName = object.displayName ?? undefined;
    message.organizer = object.organizer ?? undefined;
    message.self = object.self ?? undefined;
    message.resource = object.resource ?? undefined;
    message.optional = object.optional ?? undefined;
    message.responseStatus = object.responseStatus ?? undefined;
    message.comment = object.comment ?? undefined;
    message.additionalGuests = object.additionalGuests ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
