// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: syncs/sync_google-mail.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { SyncNangoMetadata } from "./sync";

export const protobufPackage = "syncs";

/**
 * {
 * "id": "<string>"
 * "sender": "<string>"
 * "recipients"?: "<string>"
 * "date": "<string>"
 * "subject": "<string>"
 * "body"?: "<string>"
 * "attachments": "<{ "filename": "<string>", "mimeType": "<string>", "size": "<number>", "attachmentId": "<string>" }[]>"
 * "threadId": "<string>"
 * "_nango_metadata": {
 * "deleted_at": "date | null",
 * "last_action": "ADDED | UPDATED | DELETED",
 * "first_seen_at": "date",
 * "cursor": "string",
 * "last_modified_at": "date"
 * }
 * }
 */
export interface SyncGoogleMailEmail {
  id: string;
  sender: string;
  recipients: string;
  date: Date | undefined;
  subject: string;
  body: string;
  fullContent: string;
  attachments: SyncGoogleMailEmailAttachment[];
  threadId: string;
  nangoMetadata: SyncNangoMetadata | undefined;
}

export interface SyncGoogleMailEmailAttachment {
  filename: string;
  mimeType: string;
  size: number;
  attachmentId: string;
}

function createBaseSyncGoogleMailEmail(): SyncGoogleMailEmail {
  return {
    id: "",
    sender: "",
    recipients: "",
    date: undefined,
    subject: "",
    body: "",
    fullContent: "",
    attachments: [],
    threadId: "",
    nangoMetadata: undefined,
  };
}

export const SyncGoogleMailEmail: MessageFns<SyncGoogleMailEmail> = {
  encode(message: SyncGoogleMailEmail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.sender !== "") {
      writer.uint32(18).string(message.sender);
    }
    if (message.recipients !== "") {
      writer.uint32(26).string(message.recipients);
    }
    if (message.date !== undefined) {
      Timestamp.encode(toTimestamp(message.date), writer.uint32(34).fork()).join();
    }
    if (message.subject !== "") {
      writer.uint32(42).string(message.subject);
    }
    if (message.body !== "") {
      writer.uint32(50).string(message.body);
    }
    if (message.fullContent !== "") {
      writer.uint32(58).string(message.fullContent);
    }
    for (const v of message.attachments) {
      SyncGoogleMailEmailAttachment.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.threadId !== "") {
      writer.uint32(74).string(message.threadId);
    }
    if (message.nangoMetadata !== undefined) {
      SyncNangoMetadata.encode(message.nangoMetadata, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleMailEmail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleMailEmail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sender = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.recipients = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.date = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.fullContent = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.attachments.push(SyncGoogleMailEmailAttachment.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.threadId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.nangoMetadata = SyncNangoMetadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleMailEmail {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      sender: isSet(object.sender) ? globalThis.String(object.sender) : "",
      recipients: isSet(object.recipients) ? globalThis.String(object.recipients) : "",
      date: isSet(object.date) ? fromJsonTimestamp(object.date) : undefined,
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      fullContent: isSet(object.fullContent) ? globalThis.String(object.fullContent) : "",
      attachments: globalThis.Array.isArray(object?.attachments)
        ? object.attachments.map((e: any) => SyncGoogleMailEmailAttachment.fromJSON(e))
        : [],
      threadId: isSet(object.threadId) ? globalThis.String(object.threadId) : "",
      nangoMetadata: isSet(object.nangoMetadata) ? SyncNangoMetadata.fromJSON(object.nangoMetadata) : undefined,
    };
  },

  toJSON(message: SyncGoogleMailEmail): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    if (message.recipients !== "") {
      obj.recipients = message.recipients;
    }
    if (message.date !== undefined) {
      obj.date = message.date.toISOString();
    }
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.fullContent !== "") {
      obj.fullContent = message.fullContent;
    }
    if (message.attachments?.length) {
      obj.attachments = message.attachments.map((e) => SyncGoogleMailEmailAttachment.toJSON(e));
    }
    if (message.threadId !== "") {
      obj.threadId = message.threadId;
    }
    if (message.nangoMetadata !== undefined) {
      obj.nangoMetadata = SyncNangoMetadata.toJSON(message.nangoMetadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleMailEmail>, I>>(base?: I): SyncGoogleMailEmail {
    return SyncGoogleMailEmail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleMailEmail>, I>>(object: I): SyncGoogleMailEmail {
    const message = createBaseSyncGoogleMailEmail();
    message.id = object.id ?? "";
    message.sender = object.sender ?? "";
    message.recipients = object.recipients ?? "";
    message.date = object.date ?? undefined;
    message.subject = object.subject ?? "";
    message.body = object.body ?? "";
    message.fullContent = object.fullContent ?? "";
    message.attachments = object.attachments?.map((e) => SyncGoogleMailEmailAttachment.fromPartial(e)) || [];
    message.threadId = object.threadId ?? "";
    message.nangoMetadata = (object.nangoMetadata !== undefined && object.nangoMetadata !== null)
      ? SyncNangoMetadata.fromPartial(object.nangoMetadata)
      : undefined;
    return message;
  },
};

function createBaseSyncGoogleMailEmailAttachment(): SyncGoogleMailEmailAttachment {
  return { filename: "", mimeType: "", size: 0, attachmentId: "" };
}

export const SyncGoogleMailEmailAttachment: MessageFns<SyncGoogleMailEmailAttachment> = {
  encode(message: SyncGoogleMailEmailAttachment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filename !== "") {
      writer.uint32(10).string(message.filename);
    }
    if (message.mimeType !== "") {
      writer.uint32(18).string(message.mimeType);
    }
    if (message.size !== 0) {
      writer.uint32(24).int32(message.size);
    }
    if (message.attachmentId !== "") {
      writer.uint32(34).string(message.attachmentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleMailEmailAttachment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleMailEmailAttachment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mimeType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.attachmentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleMailEmailAttachment {
    return {
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      mimeType: isSet(object.mimeType) ? globalThis.String(object.mimeType) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      attachmentId: isSet(object.attachmentId) ? globalThis.String(object.attachmentId) : "",
    };
  },

  toJSON(message: SyncGoogleMailEmailAttachment): unknown {
    const obj: any = {};
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.mimeType !== "") {
      obj.mimeType = message.mimeType;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.attachmentId !== "") {
      obj.attachmentId = message.attachmentId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleMailEmailAttachment>, I>>(base?: I): SyncGoogleMailEmailAttachment {
    return SyncGoogleMailEmailAttachment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleMailEmailAttachment>, I>>(
    object: I,
  ): SyncGoogleMailEmailAttachment {
    const message = createBaseSyncGoogleMailEmailAttachment();
    message.filename = object.filename ?? "";
    message.mimeType = object.mimeType ?? "";
    message.size = object.size ?? 0;
    message.attachmentId = object.attachmentId ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
