// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: syncs/sync.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "syncs";

export enum SyncMode {
  INCREMENTAL = 0,
  FULL_REFRESH = 1,
  FULL_REFRESH_AND_CLEAR_CACHE = 2,
  UNRECOGNIZED = -1,
}

export function syncModeFromJSON(object: any): SyncMode {
  switch (object) {
    case 0:
    case "INCREMENTAL":
      return SyncMode.INCREMENTAL;
    case 1:
    case "FULL_REFRESH":
      return SyncMode.FULL_REFRESH;
    case 2:
    case "FULL_REFRESH_AND_CLEAR_CACHE":
      return SyncMode.FULL_REFRESH_AND_CLEAR_CACHE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SyncMode.UNRECOGNIZED;
  }
}

export function syncModeToJSON(object: SyncMode): string {
  switch (object) {
    case SyncMode.INCREMENTAL:
      return "INCREMENTAL";
    case SyncMode.FULL_REFRESH:
      return "FULL_REFRESH";
    case SyncMode.FULL_REFRESH_AND_CLEAR_CACHE:
      return "FULL_REFRESH_AND_CLEAR_CACHE";
    case SyncMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SyncStatus {
  PENDING = 0,
  IN_PROGRESS = 1,
  COMPLETED = 2,
  FAILED = 3,
  PARTIALLY_COMPLETED = 4,
  UNRECOGNIZED = -1,
}

export function syncStatusFromJSON(object: any): SyncStatus {
  switch (object) {
    case 0:
    case "PENDING":
      return SyncStatus.PENDING;
    case 1:
    case "IN_PROGRESS":
      return SyncStatus.IN_PROGRESS;
    case 2:
    case "COMPLETED":
      return SyncStatus.COMPLETED;
    case 3:
    case "FAILED":
      return SyncStatus.FAILED;
    case 4:
    case "PARTIALLY_COMPLETED":
      return SyncStatus.PARTIALLY_COMPLETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SyncStatus.UNRECOGNIZED;
  }
}

export function syncStatusToJSON(object: SyncStatus): string {
  switch (object) {
    case SyncStatus.PENDING:
      return "PENDING";
    case SyncStatus.IN_PROGRESS:
      return "IN_PROGRESS";
    case SyncStatus.COMPLETED:
      return "COMPLETED";
    case SyncStatus.FAILED:
      return "FAILED";
    case SyncStatus.PARTIALLY_COMPLETED:
      return "PARTIALLY_COMPLETED";
    case SyncStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SyncInformation {
  id: string;
  nangoIntegrationId: string;
  updatedAt: Date | undefined;
  nangoNextCursor?: string | undefined;
  status: SyncStatus;
  errorMessage?: string | undefined;
}

export interface SyncNangoMetadata {
  deletedAt: Date | undefined;
  lastAction: string;
  firstSeenAt: Date | undefined;
  cursor: string;
  lastModifiedAt: Date | undefined;
}

function createBaseSyncInformation(): SyncInformation {
  return {
    id: "",
    nangoIntegrationId: "",
    updatedAt: undefined,
    nangoNextCursor: undefined,
    status: 0,
    errorMessage: undefined,
  };
}

export const SyncInformation: MessageFns<SyncInformation> = {
  encode(message: SyncInformation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.nangoIntegrationId !== "") {
      writer.uint32(18).string(message.nangoIntegrationId);
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(26).fork()).join();
    }
    if (message.nangoNextCursor !== undefined) {
      writer.uint32(34).string(message.nangoNextCursor);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.errorMessage !== undefined) {
      writer.uint32(50).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncInformation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncInformation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nangoIntegrationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nangoNextCursor = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncInformation {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      nangoIntegrationId: isSet(object.nangoIntegrationId) ? globalThis.String(object.nangoIntegrationId) : "",
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
      nangoNextCursor: isSet(object.nangoNextCursor) ? globalThis.String(object.nangoNextCursor) : undefined,
      status: isSet(object.status) ? syncStatusFromJSON(object.status) : 0,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : undefined,
    };
  },

  toJSON(message: SyncInformation): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.nangoIntegrationId !== "") {
      obj.nangoIntegrationId = message.nangoIntegrationId;
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    if (message.nangoNextCursor !== undefined) {
      obj.nangoNextCursor = message.nangoNextCursor;
    }
    if (message.status !== 0) {
      obj.status = syncStatusToJSON(message.status);
    }
    if (message.errorMessage !== undefined) {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncInformation>, I>>(base?: I): SyncInformation {
    return SyncInformation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncInformation>, I>>(object: I): SyncInformation {
    const message = createBaseSyncInformation();
    message.id = object.id ?? "";
    message.nangoIntegrationId = object.nangoIntegrationId ?? "";
    message.updatedAt = object.updatedAt ?? undefined;
    message.nangoNextCursor = object.nangoNextCursor ?? undefined;
    message.status = object.status ?? 0;
    message.errorMessage = object.errorMessage ?? undefined;
    return message;
  },
};

function createBaseSyncNangoMetadata(): SyncNangoMetadata {
  return { deletedAt: undefined, lastAction: "", firstSeenAt: undefined, cursor: "", lastModifiedAt: undefined };
}

export const SyncNangoMetadata: MessageFns<SyncNangoMetadata> = {
  encode(message: SyncNangoMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deletedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.deletedAt), writer.uint32(10).fork()).join();
    }
    if (message.lastAction !== "") {
      writer.uint32(18).string(message.lastAction);
    }
    if (message.firstSeenAt !== undefined) {
      Timestamp.encode(toTimestamp(message.firstSeenAt), writer.uint32(26).fork()).join();
    }
    if (message.cursor !== "") {
      writer.uint32(34).string(message.cursor);
    }
    if (message.lastModifiedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.lastModifiedAt), writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncNangoMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncNangoMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deletedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lastAction = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.firstSeenAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cursor = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastModifiedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncNangoMetadata {
    return {
      deletedAt: isSet(object.deletedAt) ? fromJsonTimestamp(object.deletedAt) : undefined,
      lastAction: isSet(object.lastAction) ? globalThis.String(object.lastAction) : "",
      firstSeenAt: isSet(object.firstSeenAt) ? fromJsonTimestamp(object.firstSeenAt) : undefined,
      cursor: isSet(object.cursor) ? globalThis.String(object.cursor) : "",
      lastModifiedAt: isSet(object.lastModifiedAt) ? fromJsonTimestamp(object.lastModifiedAt) : undefined,
    };
  },

  toJSON(message: SyncNangoMetadata): unknown {
    const obj: any = {};
    if (message.deletedAt !== undefined) {
      obj.deletedAt = message.deletedAt.toISOString();
    }
    if (message.lastAction !== "") {
      obj.lastAction = message.lastAction;
    }
    if (message.firstSeenAt !== undefined) {
      obj.firstSeenAt = message.firstSeenAt.toISOString();
    }
    if (message.cursor !== "") {
      obj.cursor = message.cursor;
    }
    if (message.lastModifiedAt !== undefined) {
      obj.lastModifiedAt = message.lastModifiedAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncNangoMetadata>, I>>(base?: I): SyncNangoMetadata {
    return SyncNangoMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncNangoMetadata>, I>>(object: I): SyncNangoMetadata {
    const message = createBaseSyncNangoMetadata();
    message.deletedAt = object.deletedAt ?? undefined;
    message.lastAction = object.lastAction ?? "";
    message.firstSeenAt = object.firstSeenAt ?? undefined;
    message.cursor = object.cursor ?? "";
    message.lastModifiedAt = object.lastModifiedAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
