// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: semur-engine/syncs-engine/sync_engine.proto

/* eslint-disable */

export const protobufPackage = "syncs_engine";

export enum SyncFilter {
  ADDED = 0,
  UPDATED = 1,
  DELETED = 2,
  UNRECOGNIZED = -1,
}

export function syncFilterFromJSON(object: any): SyncFilter {
  switch (object) {
    case 0:
    case "ADDED":
      return SyncFilter.ADDED;
    case 1:
    case "UPDATED":
      return SyncFilter.UPDATED;
    case 2:
    case "DELETED":
      return SyncFilter.DELETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SyncFilter.UNRECOGNIZED;
  }
}

export function syncFilterToJSON(object: SyncFilter): string {
  switch (object) {
    case SyncFilter.ADDED:
      return "ADDED";
    case SyncFilter.UPDATED:
      return "UPDATED";
    case SyncFilter.DELETED:
      return "DELETED";
    case SyncFilter.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
