// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: semur-engine/syncs-engine/sync_engine_google-mail.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SemurEngineErrorCode, semurEngineErrorCodeFromJSON, semurEngineErrorCodeToJSON } from "../semur_engine";
import { SyncFilter, syncFilterFromJSON, syncFilterToJSON } from "./sync_engine";

export const protobufPackage = "syncs_engine";

export interface SyncGoogleMailEmailsRequest {
  userId: string;
  integrationId: string;
}

export interface SyncGoogleMailEmailsFromNangoToFirestoreRequest {
  userId: string;
  integrationId: string;
  limit?: number | undefined;
  filter: SyncFilter[];
}

export interface SyncGoogleMailEmailsFromNangoToFirestoreResponse {
  error: SemurEngineErrorCode;
  message: string;
}

function createBaseSyncGoogleMailEmailsRequest(): SyncGoogleMailEmailsRequest {
  return { userId: "", integrationId: "" };
}

export const SyncGoogleMailEmailsRequest: MessageFns<SyncGoogleMailEmailsRequest> = {
  encode(message: SyncGoogleMailEmailsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.integrationId !== "") {
      writer.uint32(18).string(message.integrationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleMailEmailsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleMailEmailsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.integrationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleMailEmailsRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      integrationId: isSet(object.integrationId) ? globalThis.String(object.integrationId) : "",
    };
  },

  toJSON(message: SyncGoogleMailEmailsRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.integrationId !== "") {
      obj.integrationId = message.integrationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleMailEmailsRequest>, I>>(base?: I): SyncGoogleMailEmailsRequest {
    return SyncGoogleMailEmailsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleMailEmailsRequest>, I>>(object: I): SyncGoogleMailEmailsRequest {
    const message = createBaseSyncGoogleMailEmailsRequest();
    message.userId = object.userId ?? "";
    message.integrationId = object.integrationId ?? "";
    return message;
  },
};

function createBaseSyncGoogleMailEmailsFromNangoToFirestoreRequest(): SyncGoogleMailEmailsFromNangoToFirestoreRequest {
  return { userId: "", integrationId: "", limit: undefined, filter: [] };
}

export const SyncGoogleMailEmailsFromNangoToFirestoreRequest: MessageFns<
  SyncGoogleMailEmailsFromNangoToFirestoreRequest
> = {
  encode(
    message: SyncGoogleMailEmailsFromNangoToFirestoreRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.integrationId !== "") {
      writer.uint32(18).string(message.integrationId);
    }
    if (message.limit !== undefined) {
      writer.uint32(24).int32(message.limit);
    }
    writer.uint32(34).fork();
    for (const v of message.filter) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleMailEmailsFromNangoToFirestoreRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleMailEmailsFromNangoToFirestoreRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.integrationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.filter.push(reader.int32() as any);

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.filter.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleMailEmailsFromNangoToFirestoreRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      integrationId: isSet(object.integrationId) ? globalThis.String(object.integrationId) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : undefined,
      filter: globalThis.Array.isArray(object?.filter) ? object.filter.map((e: any) => syncFilterFromJSON(e)) : [],
    };
  },

  toJSON(message: SyncGoogleMailEmailsFromNangoToFirestoreRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.integrationId !== "") {
      obj.integrationId = message.integrationId;
    }
    if (message.limit !== undefined) {
      obj.limit = Math.round(message.limit);
    }
    if (message.filter?.length) {
      obj.filter = message.filter.map((e) => syncFilterToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleMailEmailsFromNangoToFirestoreRequest>, I>>(
    base?: I,
  ): SyncGoogleMailEmailsFromNangoToFirestoreRequest {
    return SyncGoogleMailEmailsFromNangoToFirestoreRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleMailEmailsFromNangoToFirestoreRequest>, I>>(
    object: I,
  ): SyncGoogleMailEmailsFromNangoToFirestoreRequest {
    const message = createBaseSyncGoogleMailEmailsFromNangoToFirestoreRequest();
    message.userId = object.userId ?? "";
    message.integrationId = object.integrationId ?? "";
    message.limit = object.limit ?? undefined;
    message.filter = object.filter?.map((e) => e) || [];
    return message;
  },
};

function createBaseSyncGoogleMailEmailsFromNangoToFirestoreResponse(): SyncGoogleMailEmailsFromNangoToFirestoreResponse {
  return { error: 0, message: "" };
}

export const SyncGoogleMailEmailsFromNangoToFirestoreResponse: MessageFns<
  SyncGoogleMailEmailsFromNangoToFirestoreResponse
> = {
  encode(
    message: SyncGoogleMailEmailsFromNangoToFirestoreResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.error !== 0) {
      writer.uint32(8).int32(message.error);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncGoogleMailEmailsFromNangoToFirestoreResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncGoogleMailEmailsFromNangoToFirestoreResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.error = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncGoogleMailEmailsFromNangoToFirestoreResponse {
    return {
      error: isSet(object.error) ? semurEngineErrorCodeFromJSON(object.error) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: SyncGoogleMailEmailsFromNangoToFirestoreResponse): unknown {
    const obj: any = {};
    if (message.error !== 0) {
      obj.error = semurEngineErrorCodeToJSON(message.error);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncGoogleMailEmailsFromNangoToFirestoreResponse>, I>>(
    base?: I,
  ): SyncGoogleMailEmailsFromNangoToFirestoreResponse {
    return SyncGoogleMailEmailsFromNangoToFirestoreResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncGoogleMailEmailsFromNangoToFirestoreResponse>, I>>(
    object: I,
  ): SyncGoogleMailEmailsFromNangoToFirestoreResponse {
    const message = createBaseSyncGoogleMailEmailsFromNangoToFirestoreResponse();
    message.error = object.error ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
