// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: general.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "general";

export interface PhotoFirebase {
  photo: string;
  photoRef: string;
}

function createBasePhotoFirebase(): PhotoFirebase {
  return { photo: "", photoRef: "" };
}

export const PhotoFirebase: MessageFns<PhotoFirebase> = {
  encode(message: PhotoFirebase, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.photo !== "") {
      writer.uint32(10).string(message.photo);
    }
    if (message.photoRef !== "") {
      writer.uint32(18).string(message.photoRef);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotoFirebase {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhotoFirebase();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.photo = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.photoRef = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PhotoFirebase {
    return {
      photo: isSet(object.photo) ? globalThis.String(object.photo) : "",
      photoRef: isSet(object.photoRef) ? globalThis.String(object.photoRef) : "",
    };
  },

  toJSON(message: PhotoFirebase): unknown {
    const obj: any = {};
    if (message.photo !== "") {
      obj.photo = message.photo;
    }
    if (message.photoRef !== "") {
      obj.photoRef = message.photoRef;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PhotoFirebase>, I>>(base?: I): PhotoFirebase {
    return PhotoFirebase.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PhotoFirebase>, I>>(object: I): PhotoFirebase {
    const message = createBasePhotoFirebase();
    message.photo = object.photo ?? "";
    message.photoRef = object.photoRef ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
