// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: semur-engine/semur_engine.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "semur_engine";

export enum SemurEngineErrorCode {
  NO_ERROR = 0,
  CUSTOM_ERROR = 100,
  NO_DATA_RECEIVED = 101,
  INTERNAL_ERROR = 1,
  BAD_REQUEST = 2,
  UNAUTHORIZED = 3,
  NOT_FOUND = 4,
  METHOD_NOT_ALLOWED = 5,
  CONFLICT = 6,
  TOO_MANY_REQUESTS = 7,
  UNAVAILABLE = 8,
  PERMISSION_DENIED = 9,
  /** NANGO_ERROR - Nango */
  NANGO_ERROR = 10,
  NANGO_SESSION_TOKEN_ERROR = 11,
  NANGO_CONNECTION_ERROR = 12,
  /** AGENT_ERROR - Agents */
  AGENT_ERROR = 20,
  AGENT_NO_INTEGRATION = 21,
  AGENT_MODEL_ERROR = 22,
  UNRECOGNIZED = -1,
}

export function semurEngineErrorCodeFromJSON(object: any): SemurEngineErrorCode {
  switch (object) {
    case 0:
    case "NO_ERROR":
      return SemurEngineErrorCode.NO_ERROR;
    case 100:
    case "CUSTOM_ERROR":
      return SemurEngineErrorCode.CUSTOM_ERROR;
    case 101:
    case "NO_DATA_RECEIVED":
      return SemurEngineErrorCode.NO_DATA_RECEIVED;
    case 1:
    case "INTERNAL_ERROR":
      return SemurEngineErrorCode.INTERNAL_ERROR;
    case 2:
    case "BAD_REQUEST":
      return SemurEngineErrorCode.BAD_REQUEST;
    case 3:
    case "UNAUTHORIZED":
      return SemurEngineErrorCode.UNAUTHORIZED;
    case 4:
    case "NOT_FOUND":
      return SemurEngineErrorCode.NOT_FOUND;
    case 5:
    case "METHOD_NOT_ALLOWED":
      return SemurEngineErrorCode.METHOD_NOT_ALLOWED;
    case 6:
    case "CONFLICT":
      return SemurEngineErrorCode.CONFLICT;
    case 7:
    case "TOO_MANY_REQUESTS":
      return SemurEngineErrorCode.TOO_MANY_REQUESTS;
    case 8:
    case "UNAVAILABLE":
      return SemurEngineErrorCode.UNAVAILABLE;
    case 9:
    case "PERMISSION_DENIED":
      return SemurEngineErrorCode.PERMISSION_DENIED;
    case 10:
    case "NANGO_ERROR":
      return SemurEngineErrorCode.NANGO_ERROR;
    case 11:
    case "NANGO_SESSION_TOKEN_ERROR":
      return SemurEngineErrorCode.NANGO_SESSION_TOKEN_ERROR;
    case 12:
    case "NANGO_CONNECTION_ERROR":
      return SemurEngineErrorCode.NANGO_CONNECTION_ERROR;
    case 20:
    case "AGENT_ERROR":
      return SemurEngineErrorCode.AGENT_ERROR;
    case 21:
    case "AGENT_NO_INTEGRATION":
      return SemurEngineErrorCode.AGENT_NO_INTEGRATION;
    case 22:
    case "AGENT_MODEL_ERROR":
      return SemurEngineErrorCode.AGENT_MODEL_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SemurEngineErrorCode.UNRECOGNIZED;
  }
}

export function semurEngineErrorCodeToJSON(object: SemurEngineErrorCode): string {
  switch (object) {
    case SemurEngineErrorCode.NO_ERROR:
      return "NO_ERROR";
    case SemurEngineErrorCode.CUSTOM_ERROR:
      return "CUSTOM_ERROR";
    case SemurEngineErrorCode.NO_DATA_RECEIVED:
      return "NO_DATA_RECEIVED";
    case SemurEngineErrorCode.INTERNAL_ERROR:
      return "INTERNAL_ERROR";
    case SemurEngineErrorCode.BAD_REQUEST:
      return "BAD_REQUEST";
    case SemurEngineErrorCode.UNAUTHORIZED:
      return "UNAUTHORIZED";
    case SemurEngineErrorCode.NOT_FOUND:
      return "NOT_FOUND";
    case SemurEngineErrorCode.METHOD_NOT_ALLOWED:
      return "METHOD_NOT_ALLOWED";
    case SemurEngineErrorCode.CONFLICT:
      return "CONFLICT";
    case SemurEngineErrorCode.TOO_MANY_REQUESTS:
      return "TOO_MANY_REQUESTS";
    case SemurEngineErrorCode.UNAVAILABLE:
      return "UNAVAILABLE";
    case SemurEngineErrorCode.PERMISSION_DENIED:
      return "PERMISSION_DENIED";
    case SemurEngineErrorCode.NANGO_ERROR:
      return "NANGO_ERROR";
    case SemurEngineErrorCode.NANGO_SESSION_TOKEN_ERROR:
      return "NANGO_SESSION_TOKEN_ERROR";
    case SemurEngineErrorCode.NANGO_CONNECTION_ERROR:
      return "NANGO_CONNECTION_ERROR";
    case SemurEngineErrorCode.AGENT_ERROR:
      return "AGENT_ERROR";
    case SemurEngineErrorCode.AGENT_NO_INTEGRATION:
      return "AGENT_NO_INTEGRATION";
    case SemurEngineErrorCode.AGENT_MODEL_ERROR:
      return "AGENT_MODEL_ERROR";
    case SemurEngineErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface SemurEngineResponse {
  error: SemurEngineErrorCode;
  message: string;
}

function createBaseSemurEngineResponse(): SemurEngineResponse {
  return { error: 0, message: "" };
}

export const SemurEngineResponse: MessageFns<SemurEngineResponse> = {
  encode(message: SemurEngineResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== 0) {
      writer.uint32(8).int32(message.error);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SemurEngineResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSemurEngineResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.error = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SemurEngineResponse {
    return {
      error: isSet(object.error) ? semurEngineErrorCodeFromJSON(object.error) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: SemurEngineResponse): unknown {
    const obj: any = {};
    if (message.error !== 0) {
      obj.error = semurEngineErrorCodeToJSON(message.error);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SemurEngineResponse>, I>>(base?: I): SemurEngineResponse {
    return SemurEngineResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SemurEngineResponse>, I>>(object: I): SemurEngineResponse {
    const message = createBaseSemurEngineResponse();
    message.error = object.error ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
