// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: agents/agent.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  SemurEngineErrorCode,
  semurEngineErrorCodeFromJSON,
  semurEngineErrorCodeToJSON,
} from "../semur-engine/semur_engine";

export const protobufPackage = "agents";

export enum AgentCategory {
  GENERAL = 0,
  EMAIL = 1,
  CALENDAR = 2,
  UNRECOGNIZED = -1,
}

export function agentCategoryFromJSON(object: any): AgentCategory {
  switch (object) {
    case 0:
    case "GENERAL":
      return AgentCategory.GENERAL;
    case 1:
    case "EMAIL":
      return AgentCategory.EMAIL;
    case 2:
    case "CALENDAR":
      return AgentCategory.CALENDAR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AgentCategory.UNRECOGNIZED;
  }
}

export function agentCategoryToJSON(object: AgentCategory): string {
  switch (object) {
    case AgentCategory.GENERAL:
      return "GENERAL";
    case AgentCategory.EMAIL:
      return "EMAIL";
    case AgentCategory.CALENDAR:
      return "CALENDAR";
    case AgentCategory.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AgentTool {
  /** SEMUR_CHAT_MENTION_EMAIL - SEMUR */
  SEMUR_CHAT_MENTION_EMAIL = 0,
  /** GOOGLE_MAIL_GET_EMAILS - GOOGLE MAIL */
  GOOGLE_MAIL_GET_EMAILS = 10,
  GOOGLE_MAIL_GET_EMAIL_BY_ID = 11,
  GOOGLE_MAIL_SEARCH_COMMON_FILTERS = 12,
  GOOGLE_MAIL_VECTOR_SEARCH = 13,
  GOOGLE_MAIL_GET_SYNC_INFORMATION = 14,
  GOOGLE_MAIL_SYNC = 15,
  GOOGLE_MAIL_SEND_EMAIL = 16,
  /** GOOGLE_CALENDAR_GET_EVENTS - GOOGLE CALENDAR */
  GOOGLE_CALENDAR_GET_EVENTS = 20,
  GOOGLE_CALENDAR_SEARCH_COMMON_FILTERS = 21,
  GOOGLE_CALENDAR_VECTOR_SEARCH = 22,
  GOOGLE_CALENDAR_GET_SYNC_INFORMATION = 23,
  GOOGLE_CALENDAR_SYNC = 24,
  /** OUTLOOK_MAIL_GET_EMAILS - OUTLOOK MAIL */
  OUTLOOK_MAIL_GET_EMAILS = 30,
  OUTLOOK_MAIL_GET_EMAIL_BY_ID = 31,
  OUTLOOK_MAIL_SEARCH_COMMON_FILTERS = 32,
  OUTLOOK_MAIL_VECTOR_SEARCH = 33,
  OUTLOOK_MAIL_GET_SYNC_INFORMATION = 34,
  OUTLOOK_MAIL_SYNC = 35,
  OUTLOOK_MAIL_SEND_EMAIL = 36,
  UNRECOGNIZED = -1,
}

export function agentToolFromJSON(object: any): AgentTool {
  switch (object) {
    case 0:
    case "SEMUR_CHAT_MENTION_EMAIL":
      return AgentTool.SEMUR_CHAT_MENTION_EMAIL;
    case 10:
    case "GOOGLE_MAIL_GET_EMAILS":
      return AgentTool.GOOGLE_MAIL_GET_EMAILS;
    case 11:
    case "GOOGLE_MAIL_GET_EMAIL_BY_ID":
      return AgentTool.GOOGLE_MAIL_GET_EMAIL_BY_ID;
    case 12:
    case "GOOGLE_MAIL_SEARCH_COMMON_FILTERS":
      return AgentTool.GOOGLE_MAIL_SEARCH_COMMON_FILTERS;
    case 13:
    case "GOOGLE_MAIL_VECTOR_SEARCH":
      return AgentTool.GOOGLE_MAIL_VECTOR_SEARCH;
    case 14:
    case "GOOGLE_MAIL_GET_SYNC_INFORMATION":
      return AgentTool.GOOGLE_MAIL_GET_SYNC_INFORMATION;
    case 15:
    case "GOOGLE_MAIL_SYNC":
      return AgentTool.GOOGLE_MAIL_SYNC;
    case 16:
    case "GOOGLE_MAIL_SEND_EMAIL":
      return AgentTool.GOOGLE_MAIL_SEND_EMAIL;
    case 20:
    case "GOOGLE_CALENDAR_GET_EVENTS":
      return AgentTool.GOOGLE_CALENDAR_GET_EVENTS;
    case 21:
    case "GOOGLE_CALENDAR_SEARCH_COMMON_FILTERS":
      return AgentTool.GOOGLE_CALENDAR_SEARCH_COMMON_FILTERS;
    case 22:
    case "GOOGLE_CALENDAR_VECTOR_SEARCH":
      return AgentTool.GOOGLE_CALENDAR_VECTOR_SEARCH;
    case 23:
    case "GOOGLE_CALENDAR_GET_SYNC_INFORMATION":
      return AgentTool.GOOGLE_CALENDAR_GET_SYNC_INFORMATION;
    case 24:
    case "GOOGLE_CALENDAR_SYNC":
      return AgentTool.GOOGLE_CALENDAR_SYNC;
    case 30:
    case "OUTLOOK_MAIL_GET_EMAILS":
      return AgentTool.OUTLOOK_MAIL_GET_EMAILS;
    case 31:
    case "OUTLOOK_MAIL_GET_EMAIL_BY_ID":
      return AgentTool.OUTLOOK_MAIL_GET_EMAIL_BY_ID;
    case 32:
    case "OUTLOOK_MAIL_SEARCH_COMMON_FILTERS":
      return AgentTool.OUTLOOK_MAIL_SEARCH_COMMON_FILTERS;
    case 33:
    case "OUTLOOK_MAIL_VECTOR_SEARCH":
      return AgentTool.OUTLOOK_MAIL_VECTOR_SEARCH;
    case 34:
    case "OUTLOOK_MAIL_GET_SYNC_INFORMATION":
      return AgentTool.OUTLOOK_MAIL_GET_SYNC_INFORMATION;
    case 35:
    case "OUTLOOK_MAIL_SYNC":
      return AgentTool.OUTLOOK_MAIL_SYNC;
    case 36:
    case "OUTLOOK_MAIL_SEND_EMAIL":
      return AgentTool.OUTLOOK_MAIL_SEND_EMAIL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AgentTool.UNRECOGNIZED;
  }
}

export function agentToolToJSON(object: AgentTool): string {
  switch (object) {
    case AgentTool.SEMUR_CHAT_MENTION_EMAIL:
      return "SEMUR_CHAT_MENTION_EMAIL";
    case AgentTool.GOOGLE_MAIL_GET_EMAILS:
      return "GOOGLE_MAIL_GET_EMAILS";
    case AgentTool.GOOGLE_MAIL_GET_EMAIL_BY_ID:
      return "GOOGLE_MAIL_GET_EMAIL_BY_ID";
    case AgentTool.GOOGLE_MAIL_SEARCH_COMMON_FILTERS:
      return "GOOGLE_MAIL_SEARCH_COMMON_FILTERS";
    case AgentTool.GOOGLE_MAIL_VECTOR_SEARCH:
      return "GOOGLE_MAIL_VECTOR_SEARCH";
    case AgentTool.GOOGLE_MAIL_GET_SYNC_INFORMATION:
      return "GOOGLE_MAIL_GET_SYNC_INFORMATION";
    case AgentTool.GOOGLE_MAIL_SYNC:
      return "GOOGLE_MAIL_SYNC";
    case AgentTool.GOOGLE_MAIL_SEND_EMAIL:
      return "GOOGLE_MAIL_SEND_EMAIL";
    case AgentTool.GOOGLE_CALENDAR_GET_EVENTS:
      return "GOOGLE_CALENDAR_GET_EVENTS";
    case AgentTool.GOOGLE_CALENDAR_SEARCH_COMMON_FILTERS:
      return "GOOGLE_CALENDAR_SEARCH_COMMON_FILTERS";
    case AgentTool.GOOGLE_CALENDAR_VECTOR_SEARCH:
      return "GOOGLE_CALENDAR_VECTOR_SEARCH";
    case AgentTool.GOOGLE_CALENDAR_GET_SYNC_INFORMATION:
      return "GOOGLE_CALENDAR_GET_SYNC_INFORMATION";
    case AgentTool.GOOGLE_CALENDAR_SYNC:
      return "GOOGLE_CALENDAR_SYNC";
    case AgentTool.OUTLOOK_MAIL_GET_EMAILS:
      return "OUTLOOK_MAIL_GET_EMAILS";
    case AgentTool.OUTLOOK_MAIL_GET_EMAIL_BY_ID:
      return "OUTLOOK_MAIL_GET_EMAIL_BY_ID";
    case AgentTool.OUTLOOK_MAIL_SEARCH_COMMON_FILTERS:
      return "OUTLOOK_MAIL_SEARCH_COMMON_FILTERS";
    case AgentTool.OUTLOOK_MAIL_VECTOR_SEARCH:
      return "OUTLOOK_MAIL_VECTOR_SEARCH";
    case AgentTool.OUTLOOK_MAIL_GET_SYNC_INFORMATION:
      return "OUTLOOK_MAIL_GET_SYNC_INFORMATION";
    case AgentTool.OUTLOOK_MAIL_SYNC:
      return "OUTLOOK_MAIL_SYNC";
    case AgentTool.OUTLOOK_MAIL_SEND_EMAIL:
      return "OUTLOOK_MAIL_SEND_EMAIL";
    case AgentTool.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AgentMood {
  NORMAL = 0,
  DETERMINISTIC = 1,
  CAREFUL = 2,
  CREATIVE = 3,
  WILD = 4,
  UNRECOGNIZED = -1,
}

export function agentMoodFromJSON(object: any): AgentMood {
  switch (object) {
    case 0:
    case "NORMAL":
      return AgentMood.NORMAL;
    case 1:
    case "DETERMINISTIC":
      return AgentMood.DETERMINISTIC;
    case 2:
    case "CAREFUL":
      return AgentMood.CAREFUL;
    case 3:
    case "CREATIVE":
      return AgentMood.CREATIVE;
    case 4:
    case "WILD":
      return AgentMood.WILD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AgentMood.UNRECOGNIZED;
  }
}

export function agentMoodToJSON(object: AgentMood): string {
  switch (object) {
    case AgentMood.NORMAL:
      return "NORMAL";
    case AgentMood.DETERMINISTIC:
      return "DETERMINISTIC";
    case AgentMood.CAREFUL:
      return "CAREFUL";
    case AgentMood.CREATIVE:
      return "CREATIVE";
    case AgentMood.WILD:
      return "WILD";
    case AgentMood.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface AgentChatInput {
  userId: string;
  sessionId: string;
  connectionIds: string[];
  userMessage: string;
  fastMode: boolean;
  proMode: boolean;
  agentMood?: AgentMood | undefined;
}

export interface AgentChatOutput {
  error: SemurEngineErrorCode;
  message: string;
  chatOutput?: string | undefined;
}

function createBaseAgentChatInput(): AgentChatInput {
  return {
    userId: "",
    sessionId: "",
    connectionIds: [],
    userMessage: "",
    fastMode: false,
    proMode: false,
    agentMood: undefined,
  };
}

export const AgentChatInput: MessageFns<AgentChatInput> = {
  encode(message: AgentChatInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.sessionId !== "") {
      writer.uint32(18).string(message.sessionId);
    }
    for (const v of message.connectionIds) {
      writer.uint32(26).string(v!);
    }
    if (message.userMessage !== "") {
      writer.uint32(34).string(message.userMessage);
    }
    if (message.fastMode !== false) {
      writer.uint32(40).bool(message.fastMode);
    }
    if (message.proMode !== false) {
      writer.uint32(48).bool(message.proMode);
    }
    if (message.agentMood !== undefined) {
      writer.uint32(56).int32(message.agentMood);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AgentChatInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAgentChatInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.connectionIds.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userMessage = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.fastMode = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.proMode = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.agentMood = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AgentChatInput {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      connectionIds: globalThis.Array.isArray(object?.connectionIds)
        ? object.connectionIds.map((e: any) => globalThis.String(e))
        : [],
      userMessage: isSet(object.userMessage) ? globalThis.String(object.userMessage) : "",
      fastMode: isSet(object.fastMode) ? globalThis.Boolean(object.fastMode) : false,
      proMode: isSet(object.proMode) ? globalThis.Boolean(object.proMode) : false,
      agentMood: isSet(object.agentMood) ? agentMoodFromJSON(object.agentMood) : undefined,
    };
  },

  toJSON(message: AgentChatInput): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.connectionIds?.length) {
      obj.connectionIds = message.connectionIds;
    }
    if (message.userMessage !== "") {
      obj.userMessage = message.userMessage;
    }
    if (message.fastMode !== false) {
      obj.fastMode = message.fastMode;
    }
    if (message.proMode !== false) {
      obj.proMode = message.proMode;
    }
    if (message.agentMood !== undefined) {
      obj.agentMood = agentMoodToJSON(message.agentMood);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentChatInput>, I>>(base?: I): AgentChatInput {
    return AgentChatInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentChatInput>, I>>(object: I): AgentChatInput {
    const message = createBaseAgentChatInput();
    message.userId = object.userId ?? "";
    message.sessionId = object.sessionId ?? "";
    message.connectionIds = object.connectionIds?.map((e) => e) || [];
    message.userMessage = object.userMessage ?? "";
    message.fastMode = object.fastMode ?? false;
    message.proMode = object.proMode ?? false;
    message.agentMood = object.agentMood ?? undefined;
    return message;
  },
};

function createBaseAgentChatOutput(): AgentChatOutput {
  return { error: 0, message: "", chatOutput: undefined };
}

export const AgentChatOutput: MessageFns<AgentChatOutput> = {
  encode(message: AgentChatOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== 0) {
      writer.uint32(8).int32(message.error);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.chatOutput !== undefined) {
      writer.uint32(26).string(message.chatOutput);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AgentChatOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAgentChatOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.error = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.chatOutput = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AgentChatOutput {
    return {
      error: isSet(object.error) ? semurEngineErrorCodeFromJSON(object.error) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      chatOutput: isSet(object.chatOutput) ? globalThis.String(object.chatOutput) : undefined,
    };
  },

  toJSON(message: AgentChatOutput): unknown {
    const obj: any = {};
    if (message.error !== 0) {
      obj.error = semurEngineErrorCodeToJSON(message.error);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.chatOutput !== undefined) {
      obj.chatOutput = message.chatOutput;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentChatOutput>, I>>(base?: I): AgentChatOutput {
    return AgentChatOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentChatOutput>, I>>(object: I): AgentChatOutput {
    const message = createBaseAgentChatOutput();
    message.error = object.error ?? 0;
    message.message = object.message ?? "";
    message.chatOutput = object.chatOutput ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
