// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: agents/email_assistant.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "agents";

export interface EmailAssistantMentionedEmail {
  /** TODO: This has limited options */
  id: string;
  nangoIntegrationId: string;
  provider: string;
  subject: string;
  senderName: string;
  senderEmail: string;
  snippet: string;
  date: string;
  importanceScore: number;
}

export interface EmailAssistantSuggestedReply {
  replyText: string;
  replySubject: string;
}

export interface EmailAssistantChatOutput {
  replyText: string;
  artifacts: EmailAssistantChatArtifacts | undefined;
  metadata: EmailAssistantChatMetadata | undefined;
}

export interface EmailAssistantChatArtifacts {
  mentionedEmails: EmailAssistantMentionedEmail[];
}

export interface EmailAssistantChatMetadata {
  totalEmailsAnalyzed: number;
  timeRange: string;
}

export interface EmailAssistantGenerateResponseEmailInput {
  from: string;
  to: string;
  date: string;
  subject: string;
  body: string;
}

export interface EmailAssistantGenerateResponseEmailOutput {
  responseEmailSubject: string;
  responseEmailBody: string;
}

function createBaseEmailAssistantMentionedEmail(): EmailAssistantMentionedEmail {
  return {
    id: "",
    nangoIntegrationId: "",
    provider: "",
    subject: "",
    senderName: "",
    senderEmail: "",
    snippet: "",
    date: "",
    importanceScore: 0,
  };
}

export const EmailAssistantMentionedEmail: MessageFns<EmailAssistantMentionedEmail> = {
  encode(message: EmailAssistantMentionedEmail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.nangoIntegrationId !== "") {
      writer.uint32(18).string(message.nangoIntegrationId);
    }
    if (message.provider !== "") {
      writer.uint32(26).string(message.provider);
    }
    if (message.subject !== "") {
      writer.uint32(34).string(message.subject);
    }
    if (message.senderName !== "") {
      writer.uint32(42).string(message.senderName);
    }
    if (message.senderEmail !== "") {
      writer.uint32(50).string(message.senderEmail);
    }
    if (message.snippet !== "") {
      writer.uint32(58).string(message.snippet);
    }
    if (message.date !== "") {
      writer.uint32(66).string(message.date);
    }
    if (message.importanceScore !== 0) {
      writer.uint32(77).float(message.importanceScore);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailAssistantMentionedEmail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailAssistantMentionedEmail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nangoIntegrationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.senderName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.senderEmail = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.snippet = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.importanceScore = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailAssistantMentionedEmail {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      nangoIntegrationId: isSet(object.nangoIntegrationId) ? globalThis.String(object.nangoIntegrationId) : "",
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      senderName: isSet(object.senderName) ? globalThis.String(object.senderName) : "",
      senderEmail: isSet(object.senderEmail) ? globalThis.String(object.senderEmail) : "",
      snippet: isSet(object.snippet) ? globalThis.String(object.snippet) : "",
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      importanceScore: isSet(object.importanceScore) ? globalThis.Number(object.importanceScore) : 0,
    };
  },

  toJSON(message: EmailAssistantMentionedEmail): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.nangoIntegrationId !== "") {
      obj.nangoIntegrationId = message.nangoIntegrationId;
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.senderName !== "") {
      obj.senderName = message.senderName;
    }
    if (message.senderEmail !== "") {
      obj.senderEmail = message.senderEmail;
    }
    if (message.snippet !== "") {
      obj.snippet = message.snippet;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.importanceScore !== 0) {
      obj.importanceScore = message.importanceScore;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailAssistantMentionedEmail>, I>>(base?: I): EmailAssistantMentionedEmail {
    return EmailAssistantMentionedEmail.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailAssistantMentionedEmail>, I>>(object: I): EmailAssistantMentionedEmail {
    const message = createBaseEmailAssistantMentionedEmail();
    message.id = object.id ?? "";
    message.nangoIntegrationId = object.nangoIntegrationId ?? "";
    message.provider = object.provider ?? "";
    message.subject = object.subject ?? "";
    message.senderName = object.senderName ?? "";
    message.senderEmail = object.senderEmail ?? "";
    message.snippet = object.snippet ?? "";
    message.date = object.date ?? "";
    message.importanceScore = object.importanceScore ?? 0;
    return message;
  },
};

function createBaseEmailAssistantSuggestedReply(): EmailAssistantSuggestedReply {
  return { replyText: "", replySubject: "" };
}

export const EmailAssistantSuggestedReply: MessageFns<EmailAssistantSuggestedReply> = {
  encode(message: EmailAssistantSuggestedReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.replyText !== "") {
      writer.uint32(10).string(message.replyText);
    }
    if (message.replySubject !== "") {
      writer.uint32(18).string(message.replySubject);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailAssistantSuggestedReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailAssistantSuggestedReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.replyText = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.replySubject = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailAssistantSuggestedReply {
    return {
      replyText: isSet(object.replyText) ? globalThis.String(object.replyText) : "",
      replySubject: isSet(object.replySubject) ? globalThis.String(object.replySubject) : "",
    };
  },

  toJSON(message: EmailAssistantSuggestedReply): unknown {
    const obj: any = {};
    if (message.replyText !== "") {
      obj.replyText = message.replyText;
    }
    if (message.replySubject !== "") {
      obj.replySubject = message.replySubject;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailAssistantSuggestedReply>, I>>(base?: I): EmailAssistantSuggestedReply {
    return EmailAssistantSuggestedReply.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailAssistantSuggestedReply>, I>>(object: I): EmailAssistantSuggestedReply {
    const message = createBaseEmailAssistantSuggestedReply();
    message.replyText = object.replyText ?? "";
    message.replySubject = object.replySubject ?? "";
    return message;
  },
};

function createBaseEmailAssistantChatOutput(): EmailAssistantChatOutput {
  return { replyText: "", artifacts: undefined, metadata: undefined };
}

export const EmailAssistantChatOutput: MessageFns<EmailAssistantChatOutput> = {
  encode(message: EmailAssistantChatOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.replyText !== "") {
      writer.uint32(10).string(message.replyText);
    }
    if (message.artifacts !== undefined) {
      EmailAssistantChatArtifacts.encode(message.artifacts, writer.uint32(18).fork()).join();
    }
    if (message.metadata !== undefined) {
      EmailAssistantChatMetadata.encode(message.metadata, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailAssistantChatOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailAssistantChatOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.replyText = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.artifacts = EmailAssistantChatArtifacts.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.metadata = EmailAssistantChatMetadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailAssistantChatOutput {
    return {
      replyText: isSet(object.replyText) ? globalThis.String(object.replyText) : "",
      artifacts: isSet(object.artifacts) ? EmailAssistantChatArtifacts.fromJSON(object.artifacts) : undefined,
      metadata: isSet(object.metadata) ? EmailAssistantChatMetadata.fromJSON(object.metadata) : undefined,
    };
  },

  toJSON(message: EmailAssistantChatOutput): unknown {
    const obj: any = {};
    if (message.replyText !== "") {
      obj.replyText = message.replyText;
    }
    if (message.artifacts !== undefined) {
      obj.artifacts = EmailAssistantChatArtifacts.toJSON(message.artifacts);
    }
    if (message.metadata !== undefined) {
      obj.metadata = EmailAssistantChatMetadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailAssistantChatOutput>, I>>(base?: I): EmailAssistantChatOutput {
    return EmailAssistantChatOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailAssistantChatOutput>, I>>(object: I): EmailAssistantChatOutput {
    const message = createBaseEmailAssistantChatOutput();
    message.replyText = object.replyText ?? "";
    message.artifacts = (object.artifacts !== undefined && object.artifacts !== null)
      ? EmailAssistantChatArtifacts.fromPartial(object.artifacts)
      : undefined;
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? EmailAssistantChatMetadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseEmailAssistantChatArtifacts(): EmailAssistantChatArtifacts {
  return { mentionedEmails: [] };
}

export const EmailAssistantChatArtifacts: MessageFns<EmailAssistantChatArtifacts> = {
  encode(message: EmailAssistantChatArtifacts, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.mentionedEmails) {
      EmailAssistantMentionedEmail.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailAssistantChatArtifacts {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailAssistantChatArtifacts();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mentionedEmails.push(EmailAssistantMentionedEmail.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailAssistantChatArtifacts {
    return {
      mentionedEmails: globalThis.Array.isArray(object?.mentionedEmails)
        ? object.mentionedEmails.map((e: any) => EmailAssistantMentionedEmail.fromJSON(e))
        : [],
    };
  },

  toJSON(message: EmailAssistantChatArtifacts): unknown {
    const obj: any = {};
    if (message.mentionedEmails?.length) {
      obj.mentionedEmails = message.mentionedEmails.map((e) => EmailAssistantMentionedEmail.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailAssistantChatArtifacts>, I>>(base?: I): EmailAssistantChatArtifacts {
    return EmailAssistantChatArtifacts.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailAssistantChatArtifacts>, I>>(object: I): EmailAssistantChatArtifacts {
    const message = createBaseEmailAssistantChatArtifacts();
    message.mentionedEmails = object.mentionedEmails?.map((e) => EmailAssistantMentionedEmail.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEmailAssistantChatMetadata(): EmailAssistantChatMetadata {
  return { totalEmailsAnalyzed: 0, timeRange: "" };
}

export const EmailAssistantChatMetadata: MessageFns<EmailAssistantChatMetadata> = {
  encode(message: EmailAssistantChatMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalEmailsAnalyzed !== 0) {
      writer.uint32(8).int32(message.totalEmailsAnalyzed);
    }
    if (message.timeRange !== "") {
      writer.uint32(18).string(message.timeRange);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailAssistantChatMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailAssistantChatMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalEmailsAnalyzed = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.timeRange = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailAssistantChatMetadata {
    return {
      totalEmailsAnalyzed: isSet(object.totalEmailsAnalyzed) ? globalThis.Number(object.totalEmailsAnalyzed) : 0,
      timeRange: isSet(object.timeRange) ? globalThis.String(object.timeRange) : "",
    };
  },

  toJSON(message: EmailAssistantChatMetadata): unknown {
    const obj: any = {};
    if (message.totalEmailsAnalyzed !== 0) {
      obj.totalEmailsAnalyzed = Math.round(message.totalEmailsAnalyzed);
    }
    if (message.timeRange !== "") {
      obj.timeRange = message.timeRange;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailAssistantChatMetadata>, I>>(base?: I): EmailAssistantChatMetadata {
    return EmailAssistantChatMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailAssistantChatMetadata>, I>>(object: I): EmailAssistantChatMetadata {
    const message = createBaseEmailAssistantChatMetadata();
    message.totalEmailsAnalyzed = object.totalEmailsAnalyzed ?? 0;
    message.timeRange = object.timeRange ?? "";
    return message;
  },
};

function createBaseEmailAssistantGenerateResponseEmailInput(): EmailAssistantGenerateResponseEmailInput {
  return { from: "", to: "", date: "", subject: "", body: "" };
}

export const EmailAssistantGenerateResponseEmailInput: MessageFns<EmailAssistantGenerateResponseEmailInput> = {
  encode(message: EmailAssistantGenerateResponseEmailInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(18).string(message.to);
    }
    if (message.date !== "") {
      writer.uint32(26).string(message.date);
    }
    if (message.subject !== "") {
      writer.uint32(34).string(message.subject);
    }
    if (message.body !== "") {
      writer.uint32(42).string(message.body);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailAssistantGenerateResponseEmailInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailAssistantGenerateResponseEmailInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.body = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailAssistantGenerateResponseEmailInput {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
    };
  },

  toJSON(message: EmailAssistantGenerateResponseEmailInput): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailAssistantGenerateResponseEmailInput>, I>>(
    base?: I,
  ): EmailAssistantGenerateResponseEmailInput {
    return EmailAssistantGenerateResponseEmailInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailAssistantGenerateResponseEmailInput>, I>>(
    object: I,
  ): EmailAssistantGenerateResponseEmailInput {
    const message = createBaseEmailAssistantGenerateResponseEmailInput();
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.date = object.date ?? "";
    message.subject = object.subject ?? "";
    message.body = object.body ?? "";
    return message;
  },
};

function createBaseEmailAssistantGenerateResponseEmailOutput(): EmailAssistantGenerateResponseEmailOutput {
  return { responseEmailSubject: "", responseEmailBody: "" };
}

export const EmailAssistantGenerateResponseEmailOutput: MessageFns<EmailAssistantGenerateResponseEmailOutput> = {
  encode(message: EmailAssistantGenerateResponseEmailOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseEmailSubject !== "") {
      writer.uint32(10).string(message.responseEmailSubject);
    }
    if (message.responseEmailBody !== "") {
      writer.uint32(18).string(message.responseEmailBody);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailAssistantGenerateResponseEmailOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailAssistantGenerateResponseEmailOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.responseEmailSubject = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.responseEmailBody = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailAssistantGenerateResponseEmailOutput {
    return {
      responseEmailSubject: isSet(object.responseEmailSubject) ? globalThis.String(object.responseEmailSubject) : "",
      responseEmailBody: isSet(object.responseEmailBody) ? globalThis.String(object.responseEmailBody) : "",
    };
  },

  toJSON(message: EmailAssistantGenerateResponseEmailOutput): unknown {
    const obj: any = {};
    if (message.responseEmailSubject !== "") {
      obj.responseEmailSubject = message.responseEmailSubject;
    }
    if (message.responseEmailBody !== "") {
      obj.responseEmailBody = message.responseEmailBody;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailAssistantGenerateResponseEmailOutput>, I>>(
    base?: I,
  ): EmailAssistantGenerateResponseEmailOutput {
    return EmailAssistantGenerateResponseEmailOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailAssistantGenerateResponseEmailOutput>, I>>(
    object: I,
  ): EmailAssistantGenerateResponseEmailOutput {
    const message = createBaseEmailAssistantGenerateResponseEmailOutput();
    message.responseEmailSubject = object.responseEmailSubject ?? "";
    message.responseEmailBody = object.responseEmailBody ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
